
package com.smartbt.vtsuite.connection;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.0
 * 
 */
@WebService(name = "iStreamSrvHostWSHttpGet", targetNamespace = "https://SistemasGalileo.com/Services/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface IStreamSrvHostWSHttpGet {


    /**
     * This method allows to activate a given card whose activation is pending.
     * 
     * @param pCardNumber
     * @param pTerminalCode
     * @param pRequestID
     * @return
     *     returns com.smartbt.vtsuite.connection.CardActivationResponse
     */
    @WebMethod(operationName = "WMCardActivation")
    @WebResult(name = "CardActivationResponse", targetNamespace = "https://SistemasGalileo.com/Services/", partName = "Body")
    public CardActivationResponse wmCardActivation(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pRequestID")
        String pRequestID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pTerminalCode")
        String pTerminalCode,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pCardNumber")
        String pCardNumber);

    /**
     * This method allows customized a card.
     * 
     * @param pIdType
     * @param pState
     * @param pDateOfBirth
     * @param pAddress
     * @param pCity
     * @param pIdState
     * @param pTelephoneAreaCode
     * @param pCellphone
     * @param pZipCode
     * @param pMiddleName
     * @param pTelephone
     * @param pFaxAreaCode
     * @param pLastName
     * @param pRequestID
     * @param pWorkphoneAreaCode
     * @param pCountry
     * @param pCellphoneAreaCode
     * @param pPersonTitle
     * @param pEmail
     * @param pCurrentAddress
     * @param pRBService
     * @param pFirstName
     * @param pId
     * @param pMaidenName
     * @param pWorkphone
     * @param pIdCountry
     * @param pFaxphone
     * @param pCard
     * @param pIdExpiration
     * @return
     *     returns com.smartbt.vtsuite.connection.CardCreationResponse
     */
    @WebMethod(operationName = "WMCardPersonalization")
    @WebResult(name = "CardCreationResponse", targetNamespace = "https://SistemasGalileo.com/Services/", partName = "Body")
    public CardCreationResponse wmCardPersonalization(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pRequestID")
        String pRequestID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pCard")
        String pCard,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pId")
        String pId,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pIdType")
        String pIdType,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pIdExpiration")
        String pIdExpiration,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pIdCountry")
        String pIdCountry,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pIdState")
        String pIdState,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pPersonTitle")
        String pPersonTitle,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pFirstName")
        String pFirstName,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pMiddleName")
        String pMiddleName,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pLastName")
        String pLastName,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pMaidenName")
        String pMaidenName,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pDateOfBirth")
        String pDateOfBirth,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pCountry")
        String pCountry,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pState")
        String pState,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pCity")
        String pCity,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pAddress")
        String pAddress,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pZipCode")
        String pZipCode,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pEmail")
        String pEmail,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pTelephoneAreaCode")
        String pTelephoneAreaCode,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pTelephone")
        String pTelephone,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pCellphoneAreaCode")
        String pCellphoneAreaCode,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pCellphone")
        String pCellphone,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pWorkphoneAreaCode")
        String pWorkphoneAreaCode,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pWorkphone")
        String pWorkphone,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pFaxAreaCode")
        String pFaxAreaCode,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pFaxphone")
        String pFaxphone,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pRBService")
        String pRBService,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pCurrentAddress")
        String pCurrentAddress);

    /**
     * This method allows to load funds into a given card from a virtual terminal.
     * 
     * @param pTransAmount
     * @param pCheckFee
     * @param pCardNumber
     * @param pTerminalCode
     * @param pRequestID
     * @return
     *     returns com.smartbt.vtsuite.connection.CardLoadResponse
     */
    @WebMethod(operationName = "WMCardLoad")
    @WebResult(name = "CardLoadResponse", targetNamespace = "https://SistemasGalileo.com/Services/", partName = "Body")
    public CardLoadResponse wmCardLoad(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pRequestID")
        String pRequestID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pTerminalCode")
        String pTerminalCode,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pCardNumber")
        String pCardNumber,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pTransAmount")
        String pTransAmount,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pCheckFee")
        String pCheckFee);

    /**
     * This method allows to obtain the current balance for a given card.
     * 
     * @param pCardNumber
     * @param pRequestID
     * @return
     *     returns com.smartbt.vtsuite.connection.BalanceInquiryResponse
     */
    @WebMethod(operationName = "WMBalanceInquiry")
    @WebResult(name = "BalanceInquiryResponse", targetNamespace = "https://SistemasGalileo.com/Services/", partName = "Body")
    public BalanceInquiryResponse wmBalanceInquiry(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pRequestID")
        String pRequestID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pCardNumber")
        String pCardNumber);

    /**
     * This method allows to transfer funds from a card to a bank account.
     * 
     * @param pAmount
     * @param pRoutingBankNumber
     * @param pCardNumber
     * @param pAccountNumber
     * @param pRequestID
     * @return
     *     returns com.smartbt.vtsuite.connection.CardToBankResponse
     */
    @WebMethod(operationName = "WMCardToBank")
    @WebResult(name = "CardToBankResponse", targetNamespace = "https://SistemasGalileo.com/Services/", partName = "Body")
    public CardToBankResponse wmCardToBank(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pRequestID")
        String pRequestID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pCardNumber")
        String pCardNumber,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pAccountNumber")
        String pAccountNumber,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pRoutingBankNumber")
        String pRoutingBankNumber,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pAmount")
        String pAmount);

    /**
     * This method allows to validate the status for a given card.
     * 
     * @param pAmount
     * @param pCardNumber
     * @param pRequestID
     * @return
     *     returns com.smartbt.vtsuite.connection.CardValidationResponse
     */
    @WebMethod(operationName = "WMCardValidation")
    @WebResult(name = "CardValidationResponse", targetNamespace = "https://SistemasGalileo.com/Services/", partName = "Body")
    public CardValidationResponse wmCardValidation(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pRequestID")
        String pRequestID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pCardNumber")
        String pCardNumber,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pAmount")
        String pAmount);

    /**
     * This method allows to validate if the id given is correct for the card holder.
     * 
     * @param pId
     * @param pIdType
     * @param pCardNumber
     * @param pRequestID
     * @return
     *     returns com.smartbt.vtsuite.connection.CardHolderValidationResponse
     */
    @WebMethod(operationName = "WMCardHolderValidation")
    @WebResult(name = "CardHolderValidationResponse", targetNamespace = "https://SistemasGalileo.com/Services/", partName = "Body")
    public CardHolderValidationResponse wmCardHolderValidation(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pRequestID")
        String pRequestID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pCardNumber")
        String pCardNumber,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pId")
        String pId,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pIdType")
        String pIdType);

    /**
     * This method allows to test the conectivity.
     * 
     * @param pRequestID
     * @return
     *     returns com.smartbt.vtsuite.connection.EchoResponse
     */
    @WebMethod(operationName = "WMEcho")
    @WebResult(name = "EchoResponse", targetNamespace = "https://SistemasGalileo.com/Services/", partName = "Body")
    public EchoResponse wmEcho(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pRequestID")
        String pRequestID);

    /**
     * This method allows to obtain the last transactions for a given card. The number of transactions can be specified. Additionally, it provides the starting and final balance (before and after the listed transactions).
     * 
     * @param pTransactionQuantity
     * @param pStartDate
     * @param pCardNumber
     * @param pEndDate
     * @param pRequestID
     * @return
     *     returns com.smartbt.vtsuite.connection.LastTransactionsResponse
     */
    @WebMethod(operationName = "WMLastTransactions")
    @WebResult(name = "LastTransactionsResponse", targetNamespace = "https://SistemasGalileo.com/Services/", partName = "Body")
    public LastTransactionsResponse wmLastTransactions(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pRequestID")
        String pRequestID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pCardNumber")
        String pCardNumber,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pStartDate")
        String pStartDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pEndDate")
        String pEndDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pTransactionQuantity")
        String pTransactionQuantity);

    /**
     * This method allows to load funds into a given card from a virtual terminal.
     * 
     * @param pTransAmount
     * @param pCardNumber
     * @param pTerminalCode
     * @param pRequestID
     * @return
     *     returns com.smartbt.vtsuite.connection.CashToCardResponse
     */
    @WebMethod(operationName = "WMCashToCard")
    @WebResult(name = "CashToCardResponse", targetNamespace = "https://SistemasGalileo.com/Services/", partName = "Body")
    public CashToCardResponse wmCashToCard(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pRequestID")
        String pRequestID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pTerminalCode")
        String pTerminalCode,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pCardNumber")
        String pCardNumber,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pTransAmount")
        String pTransAmount);

    /**
     * This method allows to restore a card to its pre-activation status.
     * 
     * @param pCardNumber
     * @param pRequestID
     * @return
     *     returns com.smartbt.vtsuite.connection.CardRestoreResponse
     */
    @WebMethod(operationName = "WMCardRestore")
    @WebResult(name = "CardRestoreResponse", targetNamespace = "https://SistemasGalileo.com/Services/", partName = "Body")
    public CardRestoreResponse wmCardRestore(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pRequestID")
        String pRequestID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pCardNumber")
        String pCardNumber);

}
