
package com.smartbt.vtsuite.ws.cardActivation;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * CBNegFleMaintWSV1
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.0
 * 
 */
@WebService(name = "mtvnCWCBNegFleMaintWSV1Interface", targetNamespace = "mtvnCBNegFleMaintWSV1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface MtvnCWCBNegFleMaintWSV1Interface {


    /**
     * 
     * @param messagePart
     * @return
     *     returns com.smartbt.vtsuite.ws.cardActivation.CBNegFleMaintMtvnSvcRes
     */
    @WebMethod(operationName = "CBNegFleMaint", action = "CBNegFleMaintWSV1:CBNegFleMaintMtvnSvcReqMsg")
    @WebResult(name = "CBNegFleMaintMtvnSvcRes", targetNamespace = "mtvnCWCBNegFleMaintSvcRes", partName = "messagePart")
    public CBNegFleMaintMtvnSvcRes cbNegFleMaint(
        @WebParam(name = "CBNegFleMaintMtvnSvcReq", targetNamespace = "mtvnCWCBNegFleMaintSvcReq", partName = "messagePart")
        CBNegFleMaintMtvnSvcReq messagePart);

}
