
package com.smartbt.vtsuite.boundary.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.0
 * 
 */
@WebService(name = "Scan", targetNamespace = "http://web.service.scanner.tc.com/")
public interface Scan {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "changePassword", targetNamespace = "http://web.service.scanner.tc.com/", className = "com.smartbt.vtsuite.boundary.ws.ChangePassword")
    @ResponseWrapper(localName = "changePasswordResponse", targetNamespace = "http://web.service.scanner.tc.com/", className = "com.smartbt.vtsuite.boundary.ws.ChangePasswordResponse")
    public void changePassword(
        @WebParam(name = "arg0", targetNamespace = "")
        ChangePasswordRequest arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.smartbt.vtsuite.boundary.ws.AuthRes
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "authenticate", targetNamespace = "http://web.service.scanner.tc.com/", className = "com.smartbt.vtsuite.boundary.ws.Authenticate")
    @ResponseWrapper(localName = "authenticateResponse", targetNamespace = "http://web.service.scanner.tc.com/", className = "com.smartbt.vtsuite.boundary.ws.AuthenticateResponse")
    public AuthRes authenticate(
        @WebParam(name = "arg0", targetNamespace = "")
        AuthRequest arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.smartbt.vtsuite.boundary.ws.DepositSlipRes
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "makeDepositSlip", targetNamespace = "http://web.service.scanner.tc.com/", className = "com.smartbt.vtsuite.boundary.ws.MakeDepositSlip")
    @ResponseWrapper(localName = "makeDepositSlipResponse", targetNamespace = "http://web.service.scanner.tc.com/", className = "com.smartbt.vtsuite.boundary.ws.MakeDepositSlipResponse")
    public DepositSlipRes makeDepositSlip(
        @WebParam(name = "arg0", targetNamespace = "")
        DepositSlipRequest arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "sendStats", targetNamespace = "http://web.service.scanner.tc.com/", className = "com.smartbt.vtsuite.boundary.ws.SendStats")
    @ResponseWrapper(localName = "sendStatsResponse", targetNamespace = "http://web.service.scanner.tc.com/", className = "com.smartbt.vtsuite.boundary.ws.SendStatsResponse")
    public void sendStats(
        @WebParam(name = "arg0", targetNamespace = "")
        SendStatsRequest arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "sendImage", targetNamespace = "http://web.service.scanner.tc.com/", className = "com.smartbt.vtsuite.boundary.ws.SendImage")
    @ResponseWrapper(localName = "sendImageResponse", targetNamespace = "http://web.service.scanner.tc.com/", className = "com.smartbt.vtsuite.boundary.ws.SendImageResponse")
    public void sendImage(
        @WebParam(name = "arg0", targetNamespace = "")
        SendImageRequest arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.smartbt.vtsuite.boundary.ws.CloseBatchRes
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "closeBatch", targetNamespace = "http://web.service.scanner.tc.com/", className = "com.smartbt.vtsuite.boundary.ws.CloseBatch")
    @ResponseWrapper(localName = "closeBatchResponse", targetNamespace = "http://web.service.scanner.tc.com/", className = "com.smartbt.vtsuite.boundary.ws.CloseBatchResponse")
    public CloseBatchRes closeBatch(
        @WebParam(name = "arg0", targetNamespace = "")
        CloseBatchRequest arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.smartbt.vtsuite.boundary.ws.ClientData>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getClientData", targetNamespace = "http://web.service.scanner.tc.com/", className = "com.smartbt.vtsuite.boundary.ws.GetClientData")
    @ResponseWrapper(localName = "getClientDataResponse", targetNamespace = "http://web.service.scanner.tc.com/", className = "com.smartbt.vtsuite.boundary.ws.GetClientDataResponse")
    public List<ClientData> getClientData(
        @WebParam(name = "arg0", targetNamespace = "")
        ClientRequest arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.smartbt.vtsuite.boundary.ws.RecentDepositRes
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRecentDeposits", targetNamespace = "http://web.service.scanner.tc.com/", className = "com.smartbt.vtsuite.boundary.ws.GetRecentDeposits")
    @ResponseWrapper(localName = "getRecentDepositsResponse", targetNamespace = "http://web.service.scanner.tc.com/", className = "com.smartbt.vtsuite.boundary.ws.GetRecentDepositsResponse")
    public RecentDepositRes getRecentDeposits(
        @WebParam(name = "arg0", targetNamespace = "")
        RecentDepositRequest arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.smartbt.vtsuite.boundary.ws.MessagesRes
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMessages", targetNamespace = "http://web.service.scanner.tc.com/", className = "com.smartbt.vtsuite.boundary.ws.GetMessages")
    @ResponseWrapper(localName = "getMessagesResponse", targetNamespace = "http://web.service.scanner.tc.com/", className = "com.smartbt.vtsuite.boundary.ws.GetMessagesResponse")
    public MessagesRes getMessages(
        @WebParam(name = "arg0", targetNamespace = "")
        MessagesRequest arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.smartbt.vtsuite.boundary.ws.Code>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "lookupEntity", targetNamespace = "http://web.service.scanner.tc.com/", className = "com.smartbt.vtsuite.boundary.ws.LookupEntity")
    @ResponseWrapper(localName = "lookupEntityResponse", targetNamespace = "http://web.service.scanner.tc.com/", className = "com.smartbt.vtsuite.boundary.ws.LookupEntityResponse")
    public List<Code> lookupEntity(
        @WebParam(name = "arg0", targetNamespace = "")
        LookupEntityRequest arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "forgotPassword", targetNamespace = "http://web.service.scanner.tc.com/", className = "com.smartbt.vtsuite.boundary.ws.ForgotPassword")
    @ResponseWrapper(localName = "forgotPasswordResponse", targetNamespace = "http://web.service.scanner.tc.com/", className = "com.smartbt.vtsuite.boundary.ws.ForgotPasswordResponse")
    public void forgotPassword(
        @WebParam(name = "arg0", targetNamespace = "")
        ForgotPasswordRequest arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.smartbt.vtsuite.boundary.ws.CheckAuthPollRes
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkAuthPoll", targetNamespace = "http://web.service.scanner.tc.com/", className = "com.smartbt.vtsuite.boundary.ws.CheckAuthPoll")
    @ResponseWrapper(localName = "checkAuthPollResponse", targetNamespace = "http://web.service.scanner.tc.com/", className = "com.smartbt.vtsuite.boundary.ws.CheckAuthPollResponse")
    public CheckAuthPollRes checkAuthPoll(
        @WebParam(name = "arg0", targetNamespace = "")
        CheckAuthPollRequest arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.smartbt.vtsuite.boundary.ws.CheckAuthRes
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkAuth", targetNamespace = "http://web.service.scanner.tc.com/", className = "com.smartbt.vtsuite.boundary.ws.CheckAuth")
    @ResponseWrapper(localName = "checkAuthResponse", targetNamespace = "http://web.service.scanner.tc.com/", className = "com.smartbt.vtsuite.boundary.ws.CheckAuthResponse")
    public CheckAuthRes checkAuth(
        @WebParam(name = "arg0", targetNamespace = "")
        CheckAuthRequest arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "checkAuthSubmit", targetNamespace = "http://web.service.scanner.tc.com/", className = "com.smartbt.vtsuite.boundary.ws.CheckAuthSubmit")
    @ResponseWrapper(localName = "checkAuthSubmitResponse", targetNamespace = "http://web.service.scanner.tc.com/", className = "com.smartbt.vtsuite.boundary.ws.CheckAuthSubmitResponse")
    public CheckAuthSubmitRes checkAuthSubmit(
        @WebParam(name = "arg0", targetNamespace = "")
        CheckAuthSubmitRequest arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.smartbt.vtsuite.boundary.ws.EnhancedCheckAuthPollRes
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "enhancedCheckAuthPoll", targetNamespace = "http://web.service.scanner.tc.com/", className = "com.smartbt.vtsuite.boundary.ws.EnhancedCheckAuthPoll")
    @ResponseWrapper(localName = "enhancedCheckAuthPollResponse", targetNamespace = "http://web.service.scanner.tc.com/", className = "com.smartbt.vtsuite.boundary.ws.EnhancedCheckAuthPollResponse")
    public EnhancedCheckAuthPollRes enhancedCheckAuthPoll(
        @WebParam(name = "arg0", targetNamespace = "")
        EnhancedCheckAuthPollRequest arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.smartbt.vtsuite.boundary.ws.DraftAuxDataConfig>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getClientAuxDataConfig", targetNamespace = "http://web.service.scanner.tc.com/", className = "com.smartbt.vtsuite.boundary.ws.GetClientAuxDataConfig")
    @ResponseWrapper(localName = "getClientAuxDataConfigResponse", targetNamespace = "http://web.service.scanner.tc.com/", className = "com.smartbt.vtsuite.boundary.ws.GetClientAuxDataConfigResponse")
    public List<DraftAuxDataConfig> getClientAuxDataConfig(
        @WebParam(name = "arg0", targetNamespace = "")
        ClientRequest arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.smartbt.vtsuite.boundary.ws.CheckAuthLocationConfigRes
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkAuthLocationConfig", targetNamespace = "http://web.service.scanner.tc.com/", className = "com.smartbt.vtsuite.boundary.ws.CheckAuthLocationConfig")
    @ResponseWrapper(localName = "checkAuthLocationConfigResponse", targetNamespace = "http://web.service.scanner.tc.com/", className = "com.smartbt.vtsuite.boundary.ws.CheckAuthLocationConfigResponse")
    public CheckAuthLocationConfigRes checkAuthLocationConfig(
        @WebParam(name = "arg0", targetNamespace = "")
        CheckAuthLocationConfigRequest arg0);

}
