
package com.smartbt.vtsuite.ws.changePassword;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "mtvnCWSZChgPwdWSV1", targetNamespace = "mtvnSZChgPwdWSV1", wsdlLocation = "file:/C:/Glassfish/fiss_wsdl/changePassword/SZChgPwdWSV1.wsdl")
public class MtvnCWSZChgPwdWSV1
    extends Service
{

    private final static URL MTVNCWSZCHGPWDWSV1_WSDL_LOCATION;
    private final static WebServiceException MTVNCWSZCHGPWDWSV1_EXCEPTION;
    private final static QName MTVNCWSZCHGPWDWSV1_QNAME = new QName("mtvnSZChgPwdWSV1", "mtvnCWSZChgPwdWSV1");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Glassfish/fiss_wsdl/changePassword/SZChgPwdWSV1.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MTVNCWSZCHGPWDWSV1_WSDL_LOCATION = url;
        MTVNCWSZCHGPWDWSV1_EXCEPTION = e;
    }

    public MtvnCWSZChgPwdWSV1() {
        super(__getWsdlLocation(), MTVNCWSZCHGPWDWSV1_QNAME);
    }

    public MtvnCWSZChgPwdWSV1(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns MtvnCWSZChgPwdWSV1Interface
     */
    @WebEndpoint(name = "mtvnCWSZChgPwdWSV1Port")
    public MtvnCWSZChgPwdWSV1Interface getMtvnCWSZChgPwdWSV1Port() {
        return super.getPort(new QName("mtvnSZChgPwdWSV1", "mtvnCWSZChgPwdWSV1Port"), MtvnCWSZChgPwdWSV1Interface.class);
    }

    private static URL __getWsdlLocation() {
        if (MTVNCWSZCHGPWDWSV1_EXCEPTION!= null) {
            throw MTVNCWSZCHGPWDWSV1_EXCEPTION;
        }
        return MTVNCWSZCHGPWDWSV1_WSDL_LOCATION;
    }

}
