
package com.smartbt.vtsuite.ws.changePassword;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * SZChgPwdWSV1
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.0
 * 
 */
@WebService(name = "mtvnCWSZChgPwdWSV1Interface", targetNamespace = "mtvnSZChgPwdWSV1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface MtvnCWSZChgPwdWSV1Interface {


    /**
     * 
     * @param messagePart
     * @return
     *     returns com.smartbt.vtsuite.ws.changePassword.SZChgPwdMtvnSvcRes
     */
    @WebMethod(operationName = "SZChgPwd", action = "SZChgPwdWSV1:SZChgPwdMtvnSvcReqMsg")
    @WebResult(name = "SZChgPwdMtvnSvcRes", targetNamespace = "mtvnCWSZChgPwdSvcRes", partName = "messagePart")
    public SZChgPwdMtvnSvcRes szChgPwd(
        @WebParam(name = "SZChgPwdMtvnSvcReq", targetNamespace = "mtvnCWSZChgPwdSvcReq", partName = "messagePart")
        SZChgPwdMtvnSvcReq messagePart);

}
