
package com.smartbt.vtsuite.boundary.OEWS;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.0
 * 
 */
@WebService(name = "Service1HttpPost", targetNamespace = "http://tempuri.org/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Service1HttpPost {


    /**
     * 
     * @param rutaEjecutar
     * @param datos
     * @param corresponsales
     * @param cadena
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String contrataciones(
        @WebParam(name = "cadena", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "cadena")
        String cadena,
        @WebParam(name = "Datos", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Datos")
        String datos,
        @WebParam(name = "Corresponsales", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Corresponsales")
        String corresponsales,
        @WebParam(name = "ruta_ejecutar", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ruta_ejecutar")
        String rutaEjecutar);

    /**
     * 
     * @param rutaEjecutar
     * @param datos
     * @param corresponsales
     * @param cadena
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Info")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String info(
        @WebParam(name = "cadena", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "cadena")
        String cadena,
        @WebParam(name = "Datos", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Datos")
        String datos,
        @WebParam(name = "Corresponsales", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Corresponsales")
        String corresponsales,
        @WebParam(name = "ruta_ejecutar", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ruta_ejecutar")
        String rutaEjecutar);

    /**
     * 
     * @param rutaEjecutar
     * @param datos
     * @param corresponsales
     * @param cadena
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Logs")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String logs(
        @WebParam(name = "cadena", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "cadena")
        String cadena,
        @WebParam(name = "Datos", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Datos")
        String datos,
        @WebParam(name = "Corresponsales", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Corresponsales")
        String corresponsales,
        @WebParam(name = "ruta_ejecutar", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ruta_ejecutar")
        String rutaEjecutar);

    /**
     * 
     * @param rutaEjecutar
     * @param datos
     * @param corresponsales
     * @param cadena
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Devolucion")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String devolucion(
        @WebParam(name = "cadena", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "cadena")
        String cadena,
        @WebParam(name = "Datos", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Datos")
        String datos,
        @WebParam(name = "Corresponsales", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Corresponsales")
        String corresponsales,
        @WebParam(name = "ruta_ejecutar", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ruta_ejecutar")
        String rutaEjecutar);

    /**
     * 
     * @param rutaEjecutar
     * @param datos
     * @param corresponsales
     * @param cadena
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Notificaciones")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String notificaciones(
        @WebParam(name = "cadena", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "cadena")
        String cadena,
        @WebParam(name = "Datos", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Datos")
        String datos,
        @WebParam(name = "Corresponsales", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Corresponsales")
        String corresponsales,
        @WebParam(name = "ruta_ejecutar", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ruta_ejecutar")
        String rutaEjecutar);

    /**
     * 
     * @param rutaEjecutar
     * @param datos
     * @param corresponsales
     * @param cadena
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ReportaPago")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String reportaPago(
        @WebParam(name = "cadena", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "cadena")
        String cadena,
        @WebParam(name = "Datos", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Datos")
        String datos,
        @WebParam(name = "Corresponsales", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Corresponsales")
        String corresponsales,
        @WebParam(name = "ruta_ejecutar", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ruta_ejecutar")
        String rutaEjecutar);

    /**
     * 
     * @param rutaEjecutar
     * @param datos
     * @param corresponsales
     * @param cadena
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Reverso")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String reverso(
        @WebParam(name = "cadena", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "cadena")
        String cadena,
        @WebParam(name = "Datos", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Datos")
        String datos,
        @WebParam(name = "Corresponsales", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Corresponsales")
        String corresponsales,
        @WebParam(name = "ruta_ejecutar", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ruta_ejecutar")
        String rutaEjecutar);

    /**
     * 
     * @param rutaEjecutar
     * @param datos
     * @param corresponsales
     * @param cadena
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GeneraClave")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String generaClave(
        @WebParam(name = "cadena", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "cadena")
        String cadena,
        @WebParam(name = "Datos", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Datos")
        String datos,
        @WebParam(name = "Corresponsales", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Corresponsales")
        String corresponsales,
        @WebParam(name = "ruta_ejecutar", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ruta_ejecutar")
        String rutaEjecutar);

}
