
package com.smartbt.vtsuite.boundary.OEWS;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "Service1", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://gwin.orderexpress.com.mx:8081/stored/Service1.asmx?wsdl")
public class Service1
    extends Service
{

    private final static URL SERVICE1_WSDL_LOCATION;
    private final static WebServiceException SERVICE1_EXCEPTION;
    private final static QName SERVICE1_QNAME = new QName("http://tempuri.org/", "Service1");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://gwin.orderexpress.com.mx:8081/stored/Service1.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICE1_WSDL_LOCATION = url;
        SERVICE1_EXCEPTION = e;
    }

    public Service1() {
        super(__getWsdlLocation(), SERVICE1_QNAME);
    }

    public Service1(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns Service1Soap
     */
    @WebEndpoint(name = "Service1Soap")
    public Service1Soap getService1Soap() {
        return super.getPort(new QName("http://tempuri.org/", "Service1Soap"), Service1Soap.class);
    }

    /**
     * 
     * @return
     *     returns Service1Soap
     */
    @WebEndpoint(name = "Service1Soap12")
    public Service1Soap getService1Soap12() {
        return super.getPort(new QName("http://tempuri.org/", "Service1Soap12"), Service1Soap.class);
    }

    /**
     * 
     * @return
     *     returns Service1HttpGet
     */
    @WebEndpoint(name = "Service1HttpGet")
    public Service1HttpGet getService1HttpGet() {
        return super.getPort(new QName("http://tempuri.org/", "Service1HttpGet"), Service1HttpGet.class);
    }

    /**
     * 
     * @return
     *     returns Service1HttpPost
     */
    @WebEndpoint(name = "Service1HttpPost")
    public Service1HttpPost getService1HttpPost() {
        return super.getPort(new QName("http://tempuri.org/", "Service1HttpPost"), Service1HttpPost.class);
    }

    private static URL __getWsdlLocation() {
        if (SERVICE1_EXCEPTION!= null) {
            throw SERVICE1_EXCEPTION;
        }
        return SERVICE1_WSDL_LOCATION;
    }

}
