
package com.smartbt.vtsuite.boundary.OEWS;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.0
 * 
 */
@WebService(name = "Service1Soap", targetNamespace = "http://tempuri.org/")
public interface Service1Soap {


    /**
     * 
     * @param rutaEjecutar
     * @param datos
     * @param corresponsales
     * @param cadena
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/contrataciones")
    @WebResult(name = "contratacionesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "contrataciones", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Contrataciones")
    @ResponseWrapper(localName = "contratacionesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ContratacionesResponse")
    public String contrataciones(
        @WebParam(name = "cadena", targetNamespace = "http://tempuri.org/")
        String cadena,
        @WebParam(name = "Datos", targetNamespace = "http://tempuri.org/")
        String datos,
        @WebParam(name = "Corresponsales", targetNamespace = "http://tempuri.org/")
        String corresponsales,
        @WebParam(name = "ruta_ejecutar", targetNamespace = "http://tempuri.org/")
        String rutaEjecutar);

    /**
     * 
     * @param rutaEjecutar
     * @param datos
     * @param corresponsales
     * @param cadena
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Info", action = "http://tempuri.org/Info")
    @WebResult(name = "InfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Info", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Info")
    @ResponseWrapper(localName = "InfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InfoResponse")
    public String info(
        @WebParam(name = "cadena", targetNamespace = "http://tempuri.org/")
        String cadena,
        @WebParam(name = "Datos", targetNamespace = "http://tempuri.org/")
        String datos,
        @WebParam(name = "Corresponsales", targetNamespace = "http://tempuri.org/")
        String corresponsales,
        @WebParam(name = "ruta_ejecutar", targetNamespace = "http://tempuri.org/")
        String rutaEjecutar);

    /**
     * 
     * @param rutaEjecutar
     * @param datos
     * @param corresponsales
     * @param cadena
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Logs", action = "http://tempuri.org/Logs")
    @WebResult(name = "LogsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Logs", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Logs")
    @ResponseWrapper(localName = "LogsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.LogsResponse")
    public String logs(
        @WebParam(name = "cadena", targetNamespace = "http://tempuri.org/")
        String cadena,
        @WebParam(name = "Datos", targetNamespace = "http://tempuri.org/")
        String datos,
        @WebParam(name = "Corresponsales", targetNamespace = "http://tempuri.org/")
        String corresponsales,
        @WebParam(name = "ruta_ejecutar", targetNamespace = "http://tempuri.org/")
        String rutaEjecutar);

    /**
     * 
     * @param rutaEjecutar
     * @param datos
     * @param corresponsales
     * @param cadena
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Devolucion", action = "http://tempuri.org/Devolucion")
    @WebResult(name = "DevolucionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Devolucion", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Devolucion")
    @ResponseWrapper(localName = "DevolucionResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DevolucionResponse")
    public String devolucion(
        @WebParam(name = "cadena", targetNamespace = "http://tempuri.org/")
        String cadena,
        @WebParam(name = "Datos", targetNamespace = "http://tempuri.org/")
        String datos,
        @WebParam(name = "Corresponsales", targetNamespace = "http://tempuri.org/")
        String corresponsales,
        @WebParam(name = "ruta_ejecutar", targetNamespace = "http://tempuri.org/")
        String rutaEjecutar);

    /**
     * 
     * @param rutaEjecutar
     * @param datos
     * @param corresponsales
     * @param cadena
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Notificaciones", action = "http://tempuri.org/Notificaciones")
    @WebResult(name = "NotificacionesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Notificaciones", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Notificaciones")
    @ResponseWrapper(localName = "NotificacionesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.NotificacionesResponse")
    public String notificaciones(
        @WebParam(name = "cadena", targetNamespace = "http://tempuri.org/")
        String cadena,
        @WebParam(name = "Datos", targetNamespace = "http://tempuri.org/")
        String datos,
        @WebParam(name = "Corresponsales", targetNamespace = "http://tempuri.org/")
        String corresponsales,
        @WebParam(name = "ruta_ejecutar", targetNamespace = "http://tempuri.org/")
        String rutaEjecutar);

    /**
     * 
     * @param rutaEjecutar
     * @param datos
     * @param corresponsales
     * @param cadena
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ReportaPago", action = "http://tempuri.org/ReportaPago")
    @WebResult(name = "ReportaPagoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ReportaPago", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ReportaPago")
    @ResponseWrapper(localName = "ReportaPagoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ReportaPagoResponse")
    public String reportaPago(
        @WebParam(name = "cadena", targetNamespace = "http://tempuri.org/")
        String cadena,
        @WebParam(name = "Datos", targetNamespace = "http://tempuri.org/")
        String datos,
        @WebParam(name = "Corresponsales", targetNamespace = "http://tempuri.org/")
        String corresponsales,
        @WebParam(name = "ruta_ejecutar", targetNamespace = "http://tempuri.org/")
        String rutaEjecutar);

    /**
     * 
     * @param rutaEjecutar
     * @param datos
     * @param corresponsales
     * @param cadena
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Reverso", action = "http://tempuri.org/Reverso")
    @WebResult(name = "ReversoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Reverso", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Reverso")
    @ResponseWrapper(localName = "ReversoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ReversoResponse")
    public String reverso(
        @WebParam(name = "cadena", targetNamespace = "http://tempuri.org/")
        String cadena,
        @WebParam(name = "Datos", targetNamespace = "http://tempuri.org/")
        String datos,
        @WebParam(name = "Corresponsales", targetNamespace = "http://tempuri.org/")
        String corresponsales,
        @WebParam(name = "ruta_ejecutar", targetNamespace = "http://tempuri.org/")
        String rutaEjecutar);

    /**
     * 
     * @param rutaEjecutar
     * @param datos
     * @param corresponsales
     * @param cadena
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GeneraClave", action = "http://tempuri.org/GeneraClave")
    @WebResult(name = "GeneraClaveResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GeneraClave", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraClave")
    @ResponseWrapper(localName = "GeneraClaveResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraClaveResponse")
    public String generaClave(
        @WebParam(name = "cadena", targetNamespace = "http://tempuri.org/")
        String cadena,
        @WebParam(name = "Datos", targetNamespace = "http://tempuri.org/")
        String datos,
        @WebParam(name = "Corresponsales", targetNamespace = "http://tempuri.org/")
        String corresponsales,
        @WebParam(name = "ruta_ejecutar", targetNamespace = "http://tempuri.org/")
        String rutaEjecutar);

    /**
     * 
     * @param recarga
     * @return
     *     returns org.tempuri.RescargaResponse
     */
    @WebMethod(operationName = "Recargas", action = "http://tempuri.org/Recargas")
    @WebResult(name = "RecargasResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Recargas", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Recargas")
    @ResponseWrapper(localName = "RecargasResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RecargasResponse")
    public RescargaResponse recargas(
        @WebParam(name = "recarga", targetNamespace = "http://tempuri.org/")
        Rescarga recarga);

    /**
     * 
     * @param ultimaFact
     * @return
     *     returns org.tempuri.ObtenUltimaFacResult
     */
    @WebMethod(operationName = "ObtenFactRemBen", action = "http://tempuri.org/ObtenFactRemBen")
    @WebResult(name = "ObtenFactRemBenResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ObtenFactRemBen", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenFactRemBen")
    @ResponseWrapper(localName = "ObtenFactRemBenResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenFactRemBenResponse")
    public ObtenUltimaFacResult obtenFactRemBen(
        @WebParam(name = "ultimaFact", targetNamespace = "http://tempuri.org/")
        ObtenUltimaFac ultimaFact);

    /**
     * 
     * @param ultimaFact
     * @return
     *     returns org.tempuri.ArrayOfObtenUltimaFacHResult
     */
    @WebMethod(operationName = "ObtenFactRemBenH", action = "http://tempuri.org/ObtenFactRemBenH")
    @WebResult(name = "ObtenFactRemBenHResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ObtenFactRemBenH", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenFactRemBenH")
    @ResponseWrapper(localName = "ObtenFactRemBenHResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenFactRemBenHResponse")
    public ArrayOfObtenUltimaFacHResult obtenFactRemBenH(
        @WebParam(name = "ultimaFact", targetNamespace = "http://tempuri.org/")
        ObtenUltimaFac ultimaFact);

    /**
     * 
     * @param monitor
     * @return
     *     returns org.tempuri.ArrayOfMonitorTransaccionesResult
     */
    @WebMethod(action = "http://tempuri.org/monitorT")
    @WebResult(name = "monitorTResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "monitorT", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MonitorT")
    @ResponseWrapper(localName = "monitorTResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MonitorTResponse")
    public ArrayOfMonitorTransaccionesResult monitorT(
        @WebParam(name = "monitor", targetNamespace = "http://tempuri.org/")
        MonitorTransacciones monitor);

    /**
     * 
     * @param soli
     * @return
     *     returns int
     */
    @WebMethod(operationName = "Mon_SolicContratacion", action = "http://tempuri.org/Mon_SolicContratacion")
    @WebResult(name = "Mon_SolicContratacionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Mon_SolicContratacion", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MonSolicContratacion")
    @ResponseWrapper(localName = "Mon_SolicContratacionResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MonSolicContratacionResponse")
    public int monSolicContratacion(
        @WebParam(name = "soli", targetNamespace = "http://tempuri.org/")
        SolicitudCont soli);

    /**
     * 
     * @param saldo
     * @return
     *     returns org.tempuri.ArrayOfConsultaSaldoResult
     */
    @WebMethod(operationName = "AdmonConsultaSaldo", action = "http://tempuri.org/AdmonConsultaSaldo")
    @WebResult(name = "AdmonConsultaSaldoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AdmonConsultaSaldo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AdmonConsultaSaldo")
    @ResponseWrapper(localName = "AdmonConsultaSaldoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AdmonConsultaSaldoResponse")
    public ArrayOfConsultaSaldoResult admonConsultaSaldo(
        @WebParam(name = "saldo", targetNamespace = "http://tempuri.org/")
        ConsultaSaldo saldo);

    /**
     * 
     * @param ofi
     * @return
     *     returns org.tempuri.ArrayOfOficinaResult
     */
    @WebMethod(action = "http://tempuri.org/tipoDeCambio")
    @WebResult(name = "tipoDeCambioResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "tipoDeCambio", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TipoDeCambio")
    @ResponseWrapper(localName = "tipoDeCambioResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TipoDeCambioResponse")
    public ArrayOfOficinaResult tipoDeCambio(
        @WebParam(name = "ofi", targetNamespace = "http://tempuri.org/")
        Oficina ofi);

}
