package com.smartbt.vtsuite.boundary.client.impl;

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.17 at 06:53:29 PM EDT 
//

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.smartbt.vtsuite.utils.OrderExpressConstantValues;

@XmlAccessorType( XmlAccessType.FIELD )
@XmlType( name = "", propOrder = {
    "idlote",
    "corresponsal",
    "transaccione"
} )

@XmlRootElement( name = "LOTE_ENTRADA" )
public class LOTEENTRADAD {

    @XmlElement( name = "ID_LOTE" )
    private String idlote = "NULL";
    @XmlElement( name = "CORRESPONSAL", required = true )
    private LOTEENTRADAD.CORRESPONSAL corresponsal;
    @XmlElement( name = "TRANSACCION_E", required = true )
    private LOTEENTRADAD.TRANSACCIONE transaccione;

    public LOTEENTRADAD() {
    }

    /**
     * @return the idlote
     */
    public String getIdlote() {
        return idlote;
    }

    /**
     * @param idlote the idlote to set
     */
    public void setIdlote(String idlote) {
        this.idlote = idlote;
    }

    /**
     * @return the corresponsal
     */
    public LOTEENTRADAD.CORRESPONSAL getCorresponsal() {
        return corresponsal;
    }

    /**
     * @param corresponsal the corresponsal to set
     */
    public void setCorresponsal(LOTEENTRADAD.CORRESPONSAL corresponsal) {
        this.corresponsal = corresponsal;
    }

    /**
     * @return the transaccione
     */
    public LOTEENTRADAD.TRANSACCIONE getTransaccione() {
        return transaccione;
    }

    /**
     * @param transaccione the transaccione to set
     */
    public void setTransaccione(LOTEENTRADAD.TRANSACCIONE transaccione) {
        this.transaccione = transaccione;
    }

    /************************************CORRESPONSAL**************************************/
    
    @XmlAccessorType( XmlAccessType.FIELD )
    @XmlType( name = "", propOrder = {
        "idmerchant",
        "login",
        "password"
    } )
    public static class CORRESPONSAL {

        @XmlElement( name = "ID_MERCHANT", required = true )
        private String idmerchant = OrderExpressConstantValues.ID_MERCHANT;
        @XmlElement( name = "LOGIN", required = true )
        private String login = OrderExpressConstantValues.LOGIN;
        @XmlElement( name = "PASSWORD", required = true )
        private String password = OrderExpressConstantValues.PASSWORD;

        public CORRESPONSAL() {
        }

        /**
         * @return the idmerchant
         */
        public String getIdmerchant() {
            return idmerchant;
        }

        /**
         * @param idmerchant the idmerchant to set
         */
        public void setIdmerchant(String idmerchant) {
            this.idmerchant = idmerchant;
        }

        /**
         * @return the login
         */
        public String getLogin() {
            return login;
        }

        /**
         * @param login the login to set
         */
        public void setLogin(String login) {
            this.login = login;
        }

        /**
         * @return the password
         */
        public String getPassword() {
            return password;
        }

        /**
         * @param password the password to set
         */
        public void setPassword(String password) {
            this.password = password;
        }

    }
    
/***********************************TRANSACCIONE*******************************************/
    
    @XmlAccessorType( XmlAccessType.FIELD )
    @XmlType( name = "", propOrder = {
        "requesttype",
        "idtransaccion",
        "devolucioninput"
    } )
    public static class TRANSACCIONE {

        @XmlElement( name = "REQUEST_TYPE", required = true )
        private String requesttype = OrderExpressConstantValues.REQUEST_TYPE;
        @XmlElement( name = "ID_TRANSACCION", required = true )
        private String idtransaccion = "NULL";
        @XmlElement( name = "DEVOLUCION_INPUT", required = true )
        private LOTEENTRADAD.TRANSACCIONE.DEVOLUCIONINPUT devolucioninput;

        public TRANSACCIONE() {
        }

        /**
         * @return the requesttype
         */
        public String getRequesttype() {
            return requesttype;
        }

        /**
         * @param requesttype the requesttype to set
         */
        public void setRequesttype(String requesttype) {
            this.requesttype = requesttype;
        }

        /**
         * @return the idtransaccion
         */
        public String getIdtransaccion() {
            return idtransaccion;
        }

        /**
         * @param idtransaccion the idtransaccion to set
         */
        public void setIdtransaccion(String idtransaccion) {
            this.idtransaccion = idtransaccion;
        }

        /**
         * @return the devolucioninput
         */
        public LOTEENTRADAD.TRANSACCIONE.DEVOLUCIONINPUT getDevolucioninput() {
            return devolucioninput;
        }

        /**
         * @param devolucioninput the devolucioninput to set
         */
        public void setDevolucioninput(LOTEENTRADAD.TRANSACCIONE.DEVOLUCIONINPUT devolucioninput) {
            this.devolucioninput = devolucioninput;
        }

/**********************************DEVOLUCIONINPUT***************************/
        
        @XmlAccessorType( XmlAccessType.FIELD )
        @XmlType( name = "", propOrder = {
            "autonumber",
            "idTeller"
            
        } )
        public static class DEVOLUCIONINPUT {

            @XmlElement(name = "AUTO_NUMBER", required = true)
            private String autonumber = "NULL";
            
            @XmlElement( name = "ID_TELLER", required = true )
            private String idTeller = OrderExpressConstantValues.ID_TELLER;

            public DEVOLUCIONINPUT() {
            }

            /**
             * @return the idTeller
             */
            public String getIdTeller() {
                return idTeller;
            }

            /**
             * @param idTeller the idTeller to set
             */
            public void setIdTeller(String idTeller) {
                this.idTeller = idTeller;
            }

            /**
             * @return the autonumber
             */
            public String getAutonumber() {
                return autonumber;
            }

            /**
             * @param autonumber the autonumber to set
             */
            public void setAutonumber(String autonumber) {
                this.autonumber = autonumber;
            }

        }

    }

}
