//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.08 at 02:12:15 PM EDT 
//
package com.smartbt.vtsuite.boundary.client.impl;

import com.smartbt.girocheck.servercommon.enums.ParameterName;
import com.smartbt.girocheck.servercommon.enums.TransactionType;
import com.smartbt.girocheck.servercommon.utils.IMap;
import java.util.HashMap;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.apache.commons.lang.builder.ReflectionToStringBuilder;

@XmlAccessorType( XmlAccessType.FIELD )
@XmlType( name = "", propOrder = {
    "transacciono"
} )
@XmlRootElement( name = "LOTE_SALIDA" )
public class LOTESALIDARP implements IMap {

    @XmlElement( name = "TRANSACCION_O", required = true )
    private LOTESALIDARP.TRANSACCIONO transacciono;

    public LOTESALIDARP() {
    }

    @Override
    public String toString() {
        return ReflectionToStringBuilder.reflectionToString( this );
    }

    @Override
    public Map toMap() {

        Map map = new HashMap();
        try {
            map.put(ParameterName.TRANSACTION_TYPE, TransactionType.ORDER_EXPRESS_REPORTAPAGO);
            map.put(ParameterName.AUTHO_NUMBER, getTransacciono().getReportapagooutput().getAuthonumber());
            map.put(ParameterName.OP_CODE, getTransacciono().getReportapagooutput().getOpcode());
            map.put(ParameterName.OP_CODE2, getTransacciono().getReportapagooutput().getOpcode2());

        } catch (Exception e) {
            e.printStackTrace();
        }
        return map;
    }

    /**
     * @return the transacciono
     */
    public LOTESALIDARP.TRANSACCIONO getTransacciono() {
        return transacciono;
    }

    /**
     * @param transacciono the transacciono to set
     */
    public void setTransacciono(LOTESALIDARP.TRANSACCIONO transacciono) {
        this.transacciono = transacciono;
    }

/**********************************TRANSACCIONO*******************************************/    
    
    @XmlAccessorType( XmlAccessType.FIELD )
    @XmlType( name = "", propOrder = {
        "reportapagooutput"
    } )
    public static class TRANSACCIONO {

        @XmlElement( name = "REPORTAR_PAGO_OUTPUT", required = true )
        private LOTESALIDARP.TRANSACCIONO.REPORTAPAGOOUTPUT reportapagooutput;

        public TRANSACCIONO() {
        }

        /**
         * @return the reportapagooutput
         */
        public LOTESALIDARP.TRANSACCIONO.REPORTAPAGOOUTPUT getReportapagooutput() {
            return reportapagooutput;
        }

        /**
         * @param reportapagooutput the reportapagooutput to set
         */
        public void setReportapagooutput(LOTESALIDARP.TRANSACCIONO.REPORTAPAGOOUTPUT reportapagooutput) {
            this.reportapagooutput = reportapagooutput;
        }
        
       
/************************************REPORTAPAGOOUTPUT**********************************/
        
        @XmlAccessorType( XmlAccessType.FIELD )
        @XmlType( name = "", propOrder = {
            "authonumber",
            "opcode",
            "opcode2"
        } )
        public static class REPORTAPAGOOUTPUT {

            @XmlElement( name = "AUTHO_NUMBER", required = true )
            private String authonumber;
            @XmlElement( name = "OPCODE1", required = true )
            private String opcode;
            @XmlElement( name = "OPCODE2", required = true )
            private String opcode2;

            public REPORTAPAGOOUTPUT() {
            }

            /**
             * @return the authonumber
             */
            public String getAuthonumber() {
                return authonumber;
            }

            /**
             * @param authonumber the authonumber to set
             */
            public void setAuthonumber(String authonumber) {
                this.authonumber = authonumber;
            }

            /**
             * @return the opcode
             */
            public String getOpcode() {
                return opcode;
            }

            /**
             * @param opcode the opcode to set
             */
            public void setOpcode(String opcode) {
                this.opcode = opcode;
            }

            /**
             * @return the opcode2
             */
            public String getOpcode2() {
                return opcode2;
            }

            /**
             * @param opcode2 the opcode2 to set
             */
            public void setOpcode2(String opcode2) {
                this.opcode2 = opcode2;
            }

            

        }

    }

}
