//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.08 at 02:12:15 PM EDT 
//
package com.smartbt.vtsuite.boundary.client.impl;

import com.smartbt.girocheck.servercommon.enums.ParameterName;
import com.smartbt.girocheck.servercommon.enums.TransactionType;
import com.smartbt.girocheck.servercommon.utils.CustomeLogger;
import com.smartbt.girocheck.servercommon.utils.IMap;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.apache.commons.lang.builder.ReflectionToStringBuilder;

@XmlAccessorType( XmlAccessType.FIELD )
@XmlType( name = "", propOrder = {
    "transaccionso"
} )
@XmlRootElement( name = "LOTE_SALIDA" )
public class LOTESALIDAL implements IMap {

//    @XmlElement( name = "TRANSACCION_O", required = true )
//    private LOTESALIDAL.TRANSACCIONO transacciono;
    
    @XmlElement( name = "TRANSACCION_O", required = true )
    private ArrayList<LOTESALIDAL.TRANSACCIONO> transaccionso;

    public LOTESALIDAL() {
    }
    
    @Override
    public String toString() {
        return ReflectionToStringBuilder.reflectionToString( this );
    }

    @Override
    public Map toMap() {

        Map map = new HashMap();

        //figure out of which transction i have to take the data
        try {

            CustomeLogger.Output(CustomeLogger.OutputStates.Debug, "[OrderExpressBusinessLogic] Asking for the size ", null);
            CustomeLogger.Output(CustomeLogger.OutputStates.Debug, "[OrderExpressBusinessLogic] transactionso size: " + getTransaccionso().size(), null);

            map.put(ParameterName.TRANSACTION_TYPE, TransactionType.ORDER_EXPRESS_LOGS);
            map.put(ParameterName.AUTHO_NUMBER, getTransaccionso().get(getTransaccionso().size() - 1).getLogoutput().getAuthonumber());
            map.put(ParameterName.OEDATE_TIME, getTransaccionso().get(getTransaccionso().size() - 1).getLogoutput().getDatetime());
            map.put(ParameterName.OESTATUS, getTransaccionso().get(getTransaccionso().size() - 1).getLogoutput().getStatus());
            map.put(ParameterName.OENOTES, getTransaccionso().get(getTransaccionso().size() - 1).getLogoutput().getNotes());
            map.put(ParameterName.IDTELLER, getTransaccionso().get(getTransaccionso().size() - 1).getLogoutput().getIdTeller());
            if (getTransaccionso().get(getTransaccionso().size() - 1).getLogoutput().getOpcode() != null) {
                map.put(ParameterName.OP_CODE, getTransaccionso().get(getTransaccionso().size() - 1).getLogoutput().getOpcode());
                map.put(ParameterName.OP_CODE2, getTransaccionso().get(getTransaccionso().size() - 1).getLogoutput().getOpcode2());
            }
        } catch (Exception e) {
            CustomeLogger.Output(CustomeLogger.OutputStates.Debug, "[OrderExpressBusinessLogic] Error creating the map from lotesalida class.", null);
            e.printStackTrace();
        }
        return map;
    }

    /**
     * @return the transaccionso
     */
    public ArrayList<LOTESALIDAL.TRANSACCIONO> getTransaccionso() {
        return transaccionso;
    }

    /**
     * @param transaccionso the transaccionso to set
     */
    public void setTransaccionso(ArrayList<LOTESALIDAL.TRANSACCIONO> transaccionso) {
        this.transaccionso = transaccionso;
    }

//    /**
//     * @return the transacciono
//     */
//    public LOTESALIDAL.TRANSACCIONO getTransacciono() {
//        return transacciono;
//    }
//
//    /**
//     * @param transacciono the transacciono to set
//     */
//    public void setTransacciono(LOTESALIDAL.TRANSACCIONO transacciono) {
//        this.transacciono = transacciono;
//    }
    
/********************************TRANSACCIONO**********************************************/
    
    @XmlAccessorType( XmlAccessType.FIELD )
    @XmlType( name = "", propOrder = {
        "logoutput"
    } )
    public static class TRANSACCIONO {

        @XmlElement( name = "LOG_OUTPUT", required = true )
        private LOTESALIDAL.TRANSACCIONO.LOGOUTPUT logoutput;

        public TRANSACCIONO() {
        }
        
        /**
         * @return the logoutput
         */
        public LOTESALIDAL.TRANSACCIONO.LOGOUTPUT getLogoutput() {
            return logoutput;
        }

        /**
         * @param devolucionoutput the devolucionoutput to set
         */
        public void setLogoutput(LOTESALIDAL.TRANSACCIONO.LOGOUTPUT logoutput) {
            this.logoutput = logoutput;
        }
        
/*******************************LOGOUTPUT*************************************/
        
        @XmlAccessorType( XmlAccessType.FIELD )
        @XmlType( name = "", propOrder = {
            "authonumber",
            "datetime",
            "status",
            "notes",
            "idTeller",
            "opcode",
            "opcode2"
            
        } )
        public static class LOGOUTPUT {

            @XmlElement( name = "AUTHO_NUMBER", required = true )
            private String authonumber;
            @XmlElement( name = "DATE_TIME", required = true )
            private String datetime;
            @XmlElement( name = "STATUS", required = true )
            private String status;
            @XmlElement( name = "NOTES", required = true )
            private String notes;
            @XmlElement( name = "ID_TELLER", required = true )
            private String idTeller;
            
            /******************************/
            @XmlElement( name = "OPCODE1", required = true )
            private String opcode;
            @XmlElement( name = "OPCODE2", required = true )
            private String opcode2;
            /******************************/

            public LOGOUTPUT() {
            }
            
            /**
             * @return the authonumber
             */
            public String getAuthonumber() {
                return authonumber;
            }

            /**
             * @param authonumber the authonumber to set
             */
            public void setAuthonumber(String authonumber) {
                this.authonumber = authonumber;
            }

            /**
             * @return the datetime
             */
            public String getDatetime() {
                return datetime;
            }

            /**
             * @param datetime the datetime to set
             */
            public void setDatetime(String datetime) {
                this.datetime = datetime;
            }

            /**
             * @return the status
             */
            public String getStatus() {
                return status;
            }

            /**
             * @param status the status to set
             */
            public void setStatus(String status) {
                this.status = status;
            }

            /**
             * @return the notes
             */
            public String getNotes() {
                return notes;
            }

            /**
             * @param notes the notes to set
             */
            public void setNotes(String notes) {
                this.notes = notes;
            }

            /**
             * @return the idTeller
             */
            public String getIdTeller() {
                return idTeller;
            }

            /**
             * @param idTeller the idTeller to set
             */
            public void setIdTeller(String idTeller) {
                this.idTeller = idTeller;
            }

            /**
             * @return the opcode
             */
            public String getOpcode() {
                return opcode;
            }

            /**
             * @param opcode the opcode to set
             */
            public void setOpcode(String opcode) {
                this.opcode = opcode;
            }

            /**
             * @return the opcode2
             */
            public String getOpcode2() {
                return opcode2;
            }

            /**
             * @param opcode2 the opcode2 to set
             */
            public void setOpcode2(String opcode2) {
                this.opcode2 = opcode2;
            }


        }

    }

}
