//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.08 at 02:12:15 PM EDT 
//
package com.smartbt.vtsuite.boundary.client.impl;

import com.smartbt.girocheck.servercommon.enums.ParameterName;
import com.smartbt.girocheck.servercommon.enums.TransactionType;
import com.smartbt.girocheck.servercommon.utils.IMap;
import java.util.HashMap;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.apache.commons.lang.builder.ReflectionToStringBuilder;

@XmlAccessorType( XmlAccessType.FIELD )
@XmlType( name = "", propOrder = {
    "transacciono"
} )
@XmlRootElement( name = "LOTE_SALIDA" )
public class LOTESALIDAD implements IMap {

    @XmlElement( name = "TRANSACCION_O", required = true )
    private LOTESALIDAD.TRANSACCIONO transacciono;

    public LOTESALIDAD() {
    }
    
    @Override
    public String toString() {
        return ReflectionToStringBuilder.reflectionToString( this );
    }

    @Override
    public Map toMap() {

        Map map = new HashMap();
        
        map.put( ParameterName.TRANSACTION_TYPE, TransactionType.ORDER_EXPRESS_DEVOLUCION );
        map.put( ParameterName.AUTHO_NUMBER, getTransacciono().getDevolucionoutput().getAuthonumber() );
        map.put( ParameterName.OP_CODE, getTransacciono().getDevolucionoutput().getOpcode() );
        map.put( ParameterName.OP_CODE2, getTransacciono().getDevolucionoutput().getOpcode2() );

        return map;
    }

    /**
     * @return the transacciono
     */
    public LOTESALIDAD.TRANSACCIONO getTransacciono() {
        return transacciono;
    }

    /**
     * @param transacciono the transacciono to set
     */
    public void setTransacciono(LOTESALIDAD.TRANSACCIONO transacciono) {
        this.transacciono = transacciono;
    }
    
/********************************TRANSACCIONO**********************************************/
    
    @XmlAccessorType( XmlAccessType.FIELD )
    @XmlType( name = "", propOrder = {
        "devolucionoutput"
    } )
    public static class TRANSACCIONO {

        @XmlElement( name = "DEVOLUCION_OUTPUT", required = true )
        private LOTESALIDAD.TRANSACCIONO.DEVOLUCIONOUTPUT devolucionoutput;

        public TRANSACCIONO() {
        }
        
        /**
         * @return the devolucionoutput
         */
        public LOTESALIDAD.TRANSACCIONO.DEVOLUCIONOUTPUT getDevolucionoutput() {
            return devolucionoutput;
        }

        /**
         * @param devolucionoutput the devolucionoutput to set
         */
        public void setDevolucionoutput(LOTESALIDAD.TRANSACCIONO.DEVOLUCIONOUTPUT devolucionoutput) {
            this.devolucionoutput = devolucionoutput;
        }
        
/*******************************DEVOLUCIONOUTPUT*************************************/
        
        @XmlAccessorType( XmlAccessType.FIELD )
        @XmlType( name = "", propOrder = {
            "authonumber",
            "opcode",
            "opcode2"
        } )
        public static class DEVOLUCIONOUTPUT {

            @XmlElement( name = "AUTHO_NUMBER", required = true )
            private String authonumber;
            @XmlElement( name = "OP_CODE", required = true )
            private String opcode;
            @XmlElement( name = "OP_CODE2", required = true )
            private String opcode2;

            public DEVOLUCIONOUTPUT() {
            }
            
            /**
             * @return the authonumber
             */
            public String getAuthonumber() {
                return authonumber;
            }

            /**
             * @param authonumber the authonumber to set
             */
            public void setAuthonumber(String authonumber) {
                this.authonumber = authonumber;
            }

            /**
             * @return the opcode
             */
            public String getOpcode() {
                return opcode;
            }

            /**
             * @param opcode the opcode to set
             */
            public void setOpcode(String opcode) {
                this.opcode = opcode;
            }

            /**
             * @return the opcode2
             */
            public String getOpcode2() {
                return opcode2;
            }

            /**
             * @param opcode2 the opcode2 to set
             */
            public void setOpcode2(String opcode2) {
                this.opcode2 = opcode2;
            }

        }

    }

}
