//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.17 at 06:53:29 PM EDT 
//


package com.smartbt.vtsuite.boundary.client.impl;

import javax.xml.bind.annotation.XmlRegistry;



/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.smartbt.vtsuite package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.smartbt.vtsuite
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LOTEENTRADA }
     * 
     */

    public LOTEENTRADA createLOTEENTRADA() {
        return new LOTEENTRADA();
    }

    /**
     * Create an instance of {@link LOTEENTRADA.TRANSACCIONE }
     * 
     */
    public LOTEENTRADA.TRANSACCIONE createLOTEENTRADATRANSACCIONE() {
        return new LOTEENTRADA.TRANSACCIONE();
    }

    /**
     * Create an instance of {@link LOTEENTRADA.TRANSACCIONE.CONTRATACIONINPUT }
     * 
     */
    public LOTEENTRADA.TRANSACCIONE.CONTRATACIONINPUT createLOTEENTRADATRANSACCIONECONTRATACIONINPUT() {
        return new LOTEENTRADA.TRANSACCIONE.CONTRATACIONINPUT();
    }

    /**
     * Create an instance of {@link LOTEENTRADA.TRANSACCIONE.CONTRATACIONINPUT.CLIENTEB }
     * 
     */
    public LOTEENTRADA.TRANSACCIONE.CONTRATACIONINPUT.CLIENTEB createLOTEENTRADATRANSACCIONECONTRATACIONINPUTCLIENTEB() {
        return new LOTEENTRADA.TRANSACCIONE.CONTRATACIONINPUT.CLIENTEB();
    }

    /**
     * Create an instance of {@link LOTEENTRADA.TRANSACCIONE.CONTRATACIONINPUT.CLIENTE }
     * 
     */
    public LOTEENTRADA.TRANSACCIONE.CONTRATACIONINPUT.CLIENTE createLOTEENTRADATRANSACCIONECONTRATACIONINPUTCLIENTE() {
        return new LOTEENTRADA.TRANSACCIONE.CONTRATACIONINPUT.CLIENTE();
    }

    /**
     * Create an instance of {@link LOTEENTRADA.CORRESPONSAL }
     * 
     */
    public LOTEENTRADA.CORRESPONSAL createLOTEENTRADACORRESPONSAL() {
        return new LOTEENTRADA.CORRESPONSAL();
    }

    /**
     * Create an instance of {@link LOTEENTRADA.TRANSACCIONE.CONTRATACIONINPUT.CLIENTEB.DOCUMENTACIONCLIENTEB }
     * 
     */
    public LOTEENTRADA.TRANSACCIONE.CONTRATACIONINPUT.CLIENTEB.DOCUMENTACIONCLIENTEB createLOTEENTRADATRANSACCIONECONTRATACIONINPUTCLIENTEBDOCUMENTACIONCLIENTEB() {
        return new LOTEENTRADA.TRANSACCIONE.CONTRATACIONINPUT.CLIENTEB.DOCUMENTACIONCLIENTEB();
    }

    /**
     * Create an instance of {@link LOTEENTRADA.TRANSACCIONE.CONTRATACIONINPUT.CLIENTE.DOCUMENTACIONCLIENTE }
     * 
     */
    public LOTEENTRADA.TRANSACCIONE.CONTRATACIONINPUT.CLIENTE.DOCUMENTACIONCLIENTE createLOTEENTRADATRANSACCIONECONTRATACIONINPUTCLIENTEDOCUMENTACIONCLIENTE() {
        return new LOTEENTRADA.TRANSACCIONE.CONTRATACIONINPUT.CLIENTE.DOCUMENTACIONCLIENTE();
    }

    /**
     * Create an instance of {@link LOTESALIDA }
     * 
     */
    public LOTESALIDA createLOTESALIDA() {
        return new LOTESALIDA();
    }

    /**
     * Create an instance of {@link LOTESALIDA.TRANSACCIONO }
     * 
     */
    public LOTESALIDA.TRANSACCIONO createLOTESALIDATRANSACCIONO() {
        return new LOTESALIDA.TRANSACCIONO();
    }

    /**
     * Create an instance of {@link LOTESALIDA.TRANSACCIONO.CONTRATACIONOUTPUT }
     * 
     */
    public LOTESALIDA.TRANSACCIONO.CONTRATACIONOUTPUT createLOTESALIDATRANSACCIONOCONTRATACIONOUTPUT() {
        return new LOTESALIDA.TRANSACCIONO.CONTRATACIONOUTPUT();
    }


}
