
package com.smartbt.vtsuite.ws.history.hold;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * CBHoldListInqWSV2
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.0
 * 
 */
@WebService(name = "mtvnCWCBHoldListInqWSV2Interface", targetNamespace = "mtvnCBHoldListInqWSV2")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface MtvnCWCBHoldListInqWSV2Interface {


    /**
     * 
     * @param messagePart
     * @return
     *     returns com.smartbt.vtsuite.ws.history.hold.CBHoldListInqMtvnSvcRes
     */
    @WebMethod(operationName = "CBHoldListInq", action = "CBHoldListInqWSV2:CBHoldListInqMtvnSvcReqMsg")
    @WebResult(name = "CBHoldListInqMtvnSvcRes", targetNamespace = "mtvnCWCBHoldListInqSvcRes", partName = "messagePart")
    public CBHoldListInqMtvnSvcRes cbHoldListInq(
        @WebParam(name = "CBHoldListInqMtvnSvcReq", targetNamespace = "mtvnCWCBHoldListInqSvcReq", partName = "messagePart")
        CBHoldListInqMtvnSvcReq messagePart);

}
