
package com.smartbt.vtsuite.ws.history.hold;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "mtvnCWCBHoldListInqWSV2", targetNamespace = "mtvnCBHoldListInqWSV2", wsdlLocation = "file:/C:/Glassfish/fiss_wsdl/history/hold/CBHoldListInqWSV2.wsdl")
public class MtvnCWCBHoldListInqWSV2
    extends Service
{

    private final static URL MTVNCWCBHOLDLISTINQWSV2_WSDL_LOCATION;
    private final static WebServiceException MTVNCWCBHOLDLISTINQWSV2_EXCEPTION;
    private final static QName MTVNCWCBHOLDLISTINQWSV2_QNAME = new QName("mtvnCBHoldListInqWSV2", "mtvnCWCBHoldListInqWSV2");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Glassfish/fiss_wsdl/history/hold/CBHoldListInqWSV2.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MTVNCWCBHOLDLISTINQWSV2_WSDL_LOCATION = url;
        MTVNCWCBHOLDLISTINQWSV2_EXCEPTION = e;
    }

    public MtvnCWCBHoldListInqWSV2() {
        super(__getWsdlLocation(), MTVNCWCBHOLDLISTINQWSV2_QNAME);
    }

    public MtvnCWCBHoldListInqWSV2(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns MtvnCWCBHoldListInqWSV2Interface
     */
    @WebEndpoint(name = "mtvnCWCBHoldListInqWSV2Port")
    public MtvnCWCBHoldListInqWSV2Interface getMtvnCWCBHoldListInqWSV2Port() {
        return super.getPort(new QName("mtvnCBHoldListInqWSV2", "mtvnCWCBHoldListInqWSV2Port"), MtvnCWCBHoldListInqWSV2Interface.class);
    }

    private static URL __getWsdlLocation() {
        if (MTVNCWCBHOLDLISTINQWSV2_EXCEPTION!= null) {
            throw MTVNCWCBHOLDLISTINQWSV2_EXCEPTION;
        }
        return MTVNCWCBHOLDLISTINQWSV2_WSDL_LOCATION;
    }

}
