
package com.smartbt.vtsuite.ws.cardCashing;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "mtvnCWCBPrpdAdjWSV5", targetNamespace = "mtvnCBPrpdAdjWSV5", wsdlLocation = "file:/C:/Glassfish/fiss_wsdl/cardCashing/CBPrpdAdjWSV5.wsdl")
public class MtvnCWCBPrpdAdjWSV5
    extends Service
{

    private final static URL MTVNCWCBPRPDADJWSV5_WSDL_LOCATION;
    private final static WebServiceException MTVNCWCBPRPDADJWSV5_EXCEPTION;
    private final static QName MTVNCWCBPRPDADJWSV5_QNAME = new QName("mtvnCBPrpdAdjWSV5", "mtvnCWCBPrpdAdjWSV5");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Glassfish/fiss_wsdl/cardCashing/CBPrpdAdjWSV5.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MTVNCWCBPRPDADJWSV5_WSDL_LOCATION = url;
        MTVNCWCBPRPDADJWSV5_EXCEPTION = e;
    }

    public MtvnCWCBPrpdAdjWSV5() {
        super(__getWsdlLocation(), MTVNCWCBPRPDADJWSV5_QNAME);
    }

    public MtvnCWCBPrpdAdjWSV5(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns MtvnCWCBPrpdAdjWSV5Interface
     */
    @WebEndpoint(name = "mtvnCWCBPrpdAdjWSV5Port")
    public MtvnCWCBPrpdAdjWSV5Interface getMtvnCWCBPrpdAdjWSV5Port() {
        return super.getPort(new QName("mtvnCBPrpdAdjWSV5", "mtvnCWCBPrpdAdjWSV5Port"), MtvnCWCBPrpdAdjWSV5Interface.class);
    }

    private static URL __getWsdlLocation() {
        if (MTVNCWCBPRPDADJWSV5_EXCEPTION!= null) {
            throw MTVNCWCBPRPDADJWSV5_EXCEPTION;
        }
        return MTVNCWCBPRPDADJWSV5_WSDL_LOCATION;
    }

}
