
package com.smartbt.vtsuite.ws.cardCashing;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * CBPrpdAdjWSV5
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.0
 * 
 */
@WebService(name = "mtvnCWCBPrpdAdjWSV5Interface", targetNamespace = "mtvnCBPrpdAdjWSV5")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface MtvnCWCBPrpdAdjWSV5Interface {


    /**
     * 
     * @param messagePart
     * @return
     *     returns com.smartbt.vtsuite.ws.cardCashing.CBPrpdAdjMtvnSvcRes
     */
    @WebMethod(operationName = "CBPrpdAdj", action = "CBPrpdAdjWSV5:CBPrpdAdjMtvnSvcReqMsg")
    @WebResult(name = "CBPrpdAdjMtvnSvcRes", targetNamespace = "mtvnCWCBPrpdAdjSvcRes", partName = "messagePart")
    public CBPrpdAdjMtvnSvcRes cbPrpdAdj(
        @WebParam(name = "CBPrpdAdjMtvnSvcReq", targetNamespace = "mtvnCWCBPrpdAdjSvcReq", partName = "messagePart")
        CBPrpdAdjMtvnSvcReq messagePart);

}
