
package com.smartbt.girocheck.scan;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Scan", targetNamespace = "http://scan.girocheck.smartbt.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Scan {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.smartbt.girocheck.scan.CheckAuthRes
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkAuth", targetNamespace = "http://scan.girocheck.smartbt.com/", className = "com.smartbt.girocheck.scan.CheckAuth")
    @ResponseWrapper(localName = "checkAuthResponse", targetNamespace = "http://scan.girocheck.smartbt.com/", className = "com.smartbt.girocheck.scan.CheckAuthResponse")
    @Action(input = "http://scan.girocheck.smartbt.com/Scan/checkAuthRequest", output = "http://scan.girocheck.smartbt.com/Scan/checkAuthResponse")
    public CheckAuthRes checkAuth(
        @WebParam(name = "arg0", targetNamespace = "")
        CheckAuthRequest arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.smartbt.girocheck.scan.ActivityReportRes
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "activityReport", targetNamespace = "http://scan.girocheck.smartbt.com/", className = "com.smartbt.girocheck.scan.ActivityReport")
    @ResponseWrapper(localName = "activityReportResponse", targetNamespace = "http://scan.girocheck.smartbt.com/", className = "com.smartbt.girocheck.scan.ActivityReportResponse")
    @Action(input = "http://scan.girocheck.smartbt.com/Scan/activityReportRequest", output = "http://scan.girocheck.smartbt.com/Scan/activityReportResponse")
    public ActivityReportRes activityReport(
        @WebParam(name = "arg0", targetNamespace = "")
        ActivityReportRequest arg0);
    /**
     * 
     * @param arg0
     * @return
     *     returns com.smartbt.girocheck.scan.TecnicardConfirmationRes
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "tecnicardConfirmation", targetNamespace = "http://scan.girocheck.smartbt.com/", className = "com.smartbt.girocheck.scan.TecnicardConfirmation")
    @ResponseWrapper(localName = "tecnicardConfirmationResponse", targetNamespace = "http://scan.girocheck.smartbt.com/", className = "com.smartbt.girocheck.scan.TecnicardConfirmationResponse")
    @Action(input = "http://scan.girocheck.smartbt.com/Scan/tecnicardConfirmationRequest", output = "http://scan.girocheck.smartbt.com/Scan/tecnicardConfirmationResponse")
    public TecnicardConfirmationRes tecnicardConfirmation(
        @WebParam(name = "arg0", targetNamespace = "")
        TecnicardConfirmationRequest arg0);
    /**
     * 
     * @param arg0
     * @return
     *     returns com.smartbt.girocheck.scan.CardReloadRes
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cardReload", targetNamespace = "http://scan.girocheck.smartbt.com/", className = "com.smartbt.girocheck.scan.CardReload")
    @ResponseWrapper(localName = "cardReloadResponse", targetNamespace = "http://scan.girocheck.smartbt.com/", className = "com.smartbt.girocheck.scan.CardReloadResponse")
    @Action(input = "http://scan.girocheck.smartbt.com/Scan/cardReloadRequest", output = "http://scan.girocheck.smartbt.com/Scan/cardReloadResponse")
    public CardReloadRes cardReload(
        @WebParam(name = "arg0", targetNamespace = "")
        CardReloadRequest arg0);
    /**
     * 
     * @param arg0
     * @return
     *     returns com.smartbt.girocheck.scan.CardReloadDataRes
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cardReloadData", targetNamespace = "http://scan.girocheck.smartbt.com/", className = "com.smartbt.girocheck.scan.CardReloadData")
    @ResponseWrapper(localName = "cardReloadDataResponse", targetNamespace = "http://scan.girocheck.smartbt.com/", className = "com.smartbt.girocheck.scan.CardReloadDataResponse")
    @Action(input = "http://scan.girocheck.smartbt.com/Scan/cardReloadDataRequest", output = "http://scan.girocheck.smartbt.com/Scan/cardReloadDataResponse")
    public CardReloadDataRes cardReloadData(
        @WebParam(name = "arg0", targetNamespace = "")
        CardReloadDataRequest arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "checkAuthSubmit", targetNamespace = "http://scan.girocheck.smartbt.com/", className = "com.smartbt.girocheck.scan.CheckAuthSubmit")
    @ResponseWrapper(localName = "checkAuthSubmitResponse", targetNamespace = "http://scan.girocheck.smartbt.com/", className = "com.smartbt.girocheck.scan.CheckAuthSubmitResponse")
    @Action(input = "http://scan.girocheck.smartbt.com/Scan/checkAuthSubmitRequest", output = "http://scan.girocheck.smartbt.com/Scan/checkAuthSubmitResponse")
    public CheckAuthSubmitRes checkAuthSubmit(
        @WebParam(name = "arg0", targetNamespace = "")
        CheckAuthSubmitRequest arg0);

    /**
     * 
     * @param arg0
     * @return
     * returns com.smartbt.girocheck.scan.CheckAuthLocationConfigRes
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkAuthLocationConfig", targetNamespace = "http://scan.girocheck.smartbt.com/", className = "com.smartbt.girocheck.scan.CheckAuthLocationConfig")
    @ResponseWrapper(localName = "checkAuthLocationConfigResponse", targetNamespace = "http://scan.girocheck.smartbt.com/", className = "com.smartbt.girocheck.scan.CheckAuthLocationConfigResponse")
    @Action(input = "http://scan.girocheck.smartbt.com/Scan/checkAuthLocationConfigRequest", output = "http://scan.girocheck.smartbt.com/Scan/checkAuthLocationConfigResponse")
    public CheckAuthLocationConfigRes checkAuthLocationConfig(
        @WebParam(name = "arg0", targetNamespace = "")
        CheckAuthLocationConfigRequest arg0);
  
    
    /**
     * This method allows to obtain the current balance for a given card.
     * 
     * @param arg0
     * @return
     *     returns com.smartbt.girocheck.scan.BalanceInquiryRes
     */
    @WebMethod
    @WebResult( targetNamespace  = "")
    @RequestWrapper(localName = "balanceInquiry", targetNamespace = "http://scan.girocheck.smartbt.com/", className = "com.smartbt.girocheck.scan.BalanceInquiry")
    @ResponseWrapper(localName = "balanceInquiryResponse", targetNamespace = "http://scan.girocheck.smartbt.com/", className = "com.smartbt.girocheck.scan.BalanceInquiryResponse")
    @Action(input = "http://scan.girocheck.smartbt.com/Scan/balanceInquiryRequest", output = "http://scan.girocheck.smartbt.com/Scan/balanceInquiryResponse")
    public BalanceInquiryRes balanceInquiry(
        @WebParam(name = "arg0", targetNamespace = "")
        BalanceInquiryRequest arg0);
    
    
   /**
     * This method allows to transfer funds from a card to a bank account.
     * 
     * @param pAmount
     * @param pRoutingBankNumber
     * @param pCardNumber
     * @param pAccountNumber
     * @param pRequestID
     * @return
     *     returns com.smartbt.girocheck.scan.CardToBankRes
     */
    @WebMethod
    @WebResult( targetNamespace = "")
    @RequestWrapper(localName = "cardToBank", targetNamespace = "http://scan.girocheck.smartbt.com/", className = "com.smartbt.girocheck.scan.CardToBank")
    @ResponseWrapper(localName = "cardToBankResponse", targetNamespace = "http://scan.girocheck.smartbt.com/", className = "com.smartbt.girocheck.scan.CardToBankResponse")
    public CardToBankRes cardToBank(
        @WebParam(name = "arg0", targetNamespace = "")
        CardToBankRequest arg0);
    
    @WebMethod
    @WebResult( targetNamespace = "")
    @RequestWrapper(localName = "cardToBankConfirmation", targetNamespace = "http://scan.girocheck.smartbt.com/", className = "com.smartbt.girocheck.scan.CardToBankConfirmation")
    @ResponseWrapper(localName = "cardToBankConfirmationResponse", targetNamespace = "http://scan.girocheck.smartbt.com/", className = "com.smartbt.girocheck.scan.CardToBankConfirmationResponse")
    public CardToBankConfirmationRes cardToBankConfirmation(
        @WebParam(name = "arg0", targetNamespace = "")
        CardToBankConfirmationRequest arg0);
  
}
