
package com.smartbt.vtsuite.ws.cardLoad;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "mtvnCWCBPrpdLdUnldWSV3", targetNamespace = "mtvnCBPrpdLdUnldWSV3", wsdlLocation = "file:/C:/Glassfish/fiss_wsdl/cardLoad/CBPrpdLdUnldWSV3.wsdl")
public class MtvnCWCBPrpdLdUnldWSV3
    extends Service
{

    private final static URL MTVNCWCBPRPDLDUNLDWSV3_WSDL_LOCATION;
    private final static WebServiceException MTVNCWCBPRPDLDUNLDWSV3_EXCEPTION;
    private final static QName MTVNCWCBPRPDLDUNLDWSV3_QNAME = new QName("mtvnCBPrpdLdUnldWSV3", "mtvnCWCBPrpdLdUnldWSV3");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Glassfish/fiss_wsdl/cardLoad/CBPrpdLdUnldWSV3.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MTVNCWCBPRPDLDUNLDWSV3_WSDL_LOCATION = url;
        MTVNCWCBPRPDLDUNLDWSV3_EXCEPTION = e;
    }

    public MtvnCWCBPrpdLdUnldWSV3() {
        super(__getWsdlLocation(), MTVNCWCBPRPDLDUNLDWSV3_QNAME);
    }

    public MtvnCWCBPrpdLdUnldWSV3(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns MtvnCWCBPrpdLdUnldWSV3Interface
     */
    @WebEndpoint(name = "mtvnCWCBPrpdLdUnldWSV3Port")
    public MtvnCWCBPrpdLdUnldWSV3Interface getMtvnCWCBPrpdLdUnldWSV3Port() {
        return super.getPort(new QName("mtvnCBPrpdLdUnldWSV3", "mtvnCWCBPrpdLdUnldWSV3Port"), MtvnCWCBPrpdLdUnldWSV3Interface.class);
    }

    private static URL __getWsdlLocation() {
        if (MTVNCWCBPRPDLDUNLDWSV3_EXCEPTION!= null) {
            throw MTVNCWCBPRPDLDUNLDWSV3_EXCEPTION;
        }
        return MTVNCWCBPRPDLDUNLDWSV3_WSDL_LOCATION;
    }

}
