
package com.smartbt.vtsuite.ws.cardLoad;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * CBPrpdLdUnldWSV3
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.0
 * 
 */
@WebService(name = "mtvnCWCBPrpdLdUnldWSV3Interface", targetNamespace = "mtvnCBPrpdLdUnldWSV3")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface MtvnCWCBPrpdLdUnldWSV3Interface {


    /**
     * 
     * @param messagePart
     * @return
     *     returns com.smartbt.vtsuite.ws.cardLoad.CBPrpdLdUnldMtvnSvcRes
     */
    @WebMethod(operationName = "CBPrpdLdUnld", action = "CBPrpdLdUnldWSV3:CBPrpdLdUnldMtvnSvcReqMsg")
    @WebResult(name = "CBPrpdLdUnldMtvnSvcRes", targetNamespace = "mtvnCWCBPrpdLdUnldSvcRes", partName = "messagePart")
    public CBPrpdLdUnldMtvnSvcRes cbPrpdLdUnld(
        @WebParam(name = "CBPrpdLdUnldMtvnSvcReq", targetNamespace = "mtvnCWCBPrpdLdUnldSvcReq", partName = "messagePart")
        CBPrpdLdUnldMtvnSvcReq messagePart);

}
