
package com.smartbt.girocheck.scan;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Scan", targetNamespace = "http://scan.girocheck.smartbt.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Scan {


    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "personalInfo", targetNamespace = "http://scan.girocheck.smartbt.com/", className = "com.smartbt.girocheck.scan.PersonalInfo")
    @ResponseWrapper(localName = "personalInfoResponse", targetNamespace = "http://scan.girocheck.smartbt.com/", className = "com.smartbt.girocheck.scan.PersonalInfoResponse")
    @Action(input = "http://scan.girocheck.smartbt.com/Scan/personalInfoRequest", output = "http://scan.girocheck.smartbt.com/Scan/personalInfoResponse")
    public PersonalInfoRes personalInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        PersonalInfoRequest arg0);

    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkInfo", targetNamespace = "http://scan.girocheck.smartbt.com/", className = "com.smartbt.girocheck.scan.CheckInfo")
    @ResponseWrapper(localName = "checkInfoResponse", targetNamespace = "http://scan.girocheck.smartbt.com/", className = "com.smartbt.girocheck.scan.CheckInfoResponse")
    @Action(input = "http://scan.girocheck.smartbt.com/Scan/checkInfoRequest", output = "http://scan.girocheck.smartbt.com/Scan/checkInfoResponse")
    public CheckInfoRes checkInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        CheckInfoRequest arg0);



    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "certegyInfo", targetNamespace = "http://scan.girocheck.smartbt.com/", className = "com.smartbt.girocheck.scan.CertegyInfo")
    @ResponseWrapper(localName = "certegyInfoResponse", targetNamespace = "http://scan.girocheck.smartbt.com/", className = "com.smartbt.girocheck.scan.CertegyInfoResponse")
    @Action(input = "http://scan.girocheck.smartbt.com/Scan/certegyInfoRequest", output = "http://scan.girocheck.smartbt.com/Scan/certegyInfoResponse")
    public CertegyInfoRes certegyInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        CertegyInfoRequest arg0);
}
