
package com.smartbt.vtsuite.ws.history.general;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * CBHistTxnInqWSV7
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.0
 * 
 */
@WebService(name = "mtvnCWCBHistTxnInqWSV7Interface", targetNamespace = "mtvnCBHistTxnInqWSV7")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface MtvnCWCBHistTxnInqWSV7Interface {


    /**
     * 
     * @param messagePart
     * @return
     *     returns com.smartbt.vtsuite.ws.history.general.CBHistTxnInqMtvnSvcRes
     */
    @WebMethod(operationName = "CBHistTxnInq", action = "CBHistTxnInqWSV7:CBHistTxnInqMtvnSvcReqMsg")
    @WebResult(name = "CBHistTxnInqMtvnSvcRes", targetNamespace = "mtvnCWCBHistTxnInqSvcRes", partName = "messagePart")
    public CBHistTxnInqMtvnSvcRes cbHistTxnInq(
        @WebParam(name = "CBHistTxnInqMtvnSvcReq", targetNamespace = "mtvnCWCBHistTxnInqSvcReq", partName = "messagePart")
        CBHistTxnInqMtvnSvcReq messagePart);

}
