
package com.smartbt.vtsuite.ws.history.general;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "mtvnCWCBHistTxnInqWSV7", targetNamespace = "mtvnCBHistTxnInqWSV7", wsdlLocation = "file:/C:/Glassfish/fiss_wsdl/history/general/CBHistTxnInqWSV7.wsdl")
public class MtvnCWCBHistTxnInqWSV7
    extends Service
{

    private final static URL MTVNCWCBHISTTXNINQWSV7_WSDL_LOCATION;
    private final static WebServiceException MTVNCWCBHISTTXNINQWSV7_EXCEPTION;
    private final static QName MTVNCWCBHISTTXNINQWSV7_QNAME = new QName("mtvnCBHistTxnInqWSV7", "mtvnCWCBHistTxnInqWSV7");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Glassfish/fiss_wsdl/history/general/CBHistTxnInqWSV7.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MTVNCWCBHISTTXNINQWSV7_WSDL_LOCATION = url;
        MTVNCWCBHISTTXNINQWSV7_EXCEPTION = e;
    }

    public MtvnCWCBHistTxnInqWSV7() {
        super(__getWsdlLocation(), MTVNCWCBHISTTXNINQWSV7_QNAME);
    }

    public MtvnCWCBHistTxnInqWSV7(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns MtvnCWCBHistTxnInqWSV7Interface
     */
    @WebEndpoint(name = "mtvnCWCBHistTxnInqWSV7Port")
    public MtvnCWCBHistTxnInqWSV7Interface getMtvnCWCBHistTxnInqWSV7Port() {
        return super.getPort(new QName("mtvnCBHistTxnInqWSV7", "mtvnCWCBHistTxnInqWSV7Port"), MtvnCWCBHistTxnInqWSV7Interface.class);
    }

    private static URL __getWsdlLocation() {
        if (MTVNCWCBHISTTXNINQWSV7_EXCEPTION!= null) {
            throw MTVNCWCBHISTTXNINQWSV7_EXCEPTION;
        }
        return MTVNCWCBHISTTXNINQWSV7_WSDL_LOCATION;
    }

}
