
package com.smartbt.vtsuite.boundary.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "WSServiceException", targetNamespace = "http://web.service.fileloader.tc.com/")
public class WSServiceException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private FaultDetail faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public WSServiceException(String message, FaultDetail faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public WSServiceException(String message, FaultDetail faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.smartbt.vtsuite.boundary.ws.FaultDetail
     */
    public FaultDetail getFaultInfo() {
        return faultInfo;
    }

}
