
package com.smartbt.vtsuite.boundary;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.0
 * 
 */
@WebService(name = "PCA", targetNamespace = "http://fis.certegy.pca.com/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PCA {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.smartbt.vtsuite.boundary.PCAResponse
     */
    @WebMethod(action = "authorize")
    @WebResult(name = "AuthorizeResponse", targetNamespace = "http://fis.certegy.pca.com/", partName = "parameters")
    public PCAResponse authorize(
        @WebParam(name = "AuthorizeRequest", targetNamespace = "http://fis.certegy.pca.com/", partName = "parameters")
        PCARequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.smartbt.vtsuite.boundary.PCAReverseResponse
     */
    @WebMethod(action = "reverse")
    @WebResult(name = "ReverseResponse", targetNamespace = "http://fis.certegy.pca.com/", partName = "parameters")
    public PCAReverseResponse reverse(
        @WebParam(name = "ReverseRequest", targetNamespace = "http://fis.certegy.pca.com/", partName = "parameters")
        PCAReverseRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.smartbt.vtsuite.boundary.PCAEchoResponse
     */
    @WebMethod(action = "echo")
    @WebResult(name = "EchoResponse", targetNamespace = "http://fis.certegy.pca.com/", partName = "parameters")
    public PCAEchoResponse echo(
        @WebParam(name = "EchoRequest", targetNamespace = "http://fis.certegy.pca.com/", partName = "parameters")
        PCAEchoRequest parameters);

}
