
package com.smartbt.vtsuite.ws.cardPersonalization;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "mtvnCWCBNmeAddrChgWSV13", targetNamespace = "mtvnCBNmeAddrChgWSV13", wsdlLocation = "file:/C:/Glassfish/fiss_wsdl/cardPersonalization/CBNmeAddrChgWSV13.wsdl")
public class MtvnCWCBNmeAddrChgWSV13
    extends Service
{

    private final static URL MTVNCWCBNMEADDRCHGWSV13_WSDL_LOCATION;
    private final static WebServiceException MTVNCWCBNMEADDRCHGWSV13_EXCEPTION;
    private final static QName MTVNCWCBNMEADDRCHGWSV13_QNAME = new QName("mtvnCBNmeAddrChgWSV13", "mtvnCWCBNmeAddrChgWSV13");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Glassfish/fiss_wsdl/cardPersonalization/CBNmeAddrChgWSV13.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MTVNCWCBNMEADDRCHGWSV13_WSDL_LOCATION = url;
        MTVNCWCBNMEADDRCHGWSV13_EXCEPTION = e;
    }

    public MtvnCWCBNmeAddrChgWSV13() {
        super(__getWsdlLocation(), MTVNCWCBNMEADDRCHGWSV13_QNAME);
    }

    public MtvnCWCBNmeAddrChgWSV13(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns MtvnCWCBNmeAddrChgWSV13Interface
     */
    @WebEndpoint(name = "mtvnCWCBNmeAddrChgWSV13Port")
    public MtvnCWCBNmeAddrChgWSV13Interface getMtvnCWCBNmeAddrChgWSV13Port() {
        return super.getPort(new QName("mtvnCBNmeAddrChgWSV13", "mtvnCWCBNmeAddrChgWSV13Port"), MtvnCWCBNmeAddrChgWSV13Interface.class);
    }

    private static URL __getWsdlLocation() {
        if (MTVNCWCBNMEADDRCHGWSV13_EXCEPTION!= null) {
            throw MTVNCWCBNMEADDRCHGWSV13_EXCEPTION;
        }
        return MTVNCWCBNMEADDRCHGWSV13_WSDL_LOCATION;
    }

}
