
package com.smartbt.vtsuite.ws.cardPersonalization;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * CBNmeAddrChgWSV13
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.0
 * 
 */
@WebService(name = "mtvnCWCBNmeAddrChgWSV13Interface", targetNamespace = "mtvnCBNmeAddrChgWSV13")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface MtvnCWCBNmeAddrChgWSV13Interface {


    /**
     * 
     * @param messagePart
     * @return
     *     returns com.smartbt.vtsuite.ws.cardPersonalization.CBNmeAddrChgMtvnSvcRes
     */
    @WebMethod(operationName = "CBNmeAddrChg", action = "CBNmeAddrChgWSV13:CBNmeAddrChgMtvnSvcReqMsg")
    @WebResult(name = "CBNmeAddrChgMtvnSvcRes", targetNamespace = "mtvnCWCBNmeAddrChgSvcRes", partName = "messagePart")
    public CBNmeAddrChgMtvnSvcRes cbNmeAddrChg(
        @WebParam(name = "CBNmeAddrChgMtvnSvcReq", targetNamespace = "mtvnCWCBNmeAddrChgSvcReq", partName = "messagePart")
        CBNmeAddrChgMtvnSvcReq messagePart);

}
