
package com.smartbt.vtsuite.ws.balanceInquiry;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "mtvnCWCBAcctInqWSV15", targetNamespace = "mtvnCBAcctInqWSV15", wsdlLocation = "file:/C:/Glassfish/fiss_wsdl/balanceInquiry/CBAcctInqWSV15.wsdl")
public class MtvnCWCBAcctInqWSV15
    extends Service
{

    private final static URL MTVNCWCBACCTINQWSV15_WSDL_LOCATION;
    private final static WebServiceException MTVNCWCBACCTINQWSV15_EXCEPTION;
    private final static QName MTVNCWCBACCTINQWSV15_QNAME = new QName("mtvnCBAcctInqWSV15", "mtvnCWCBAcctInqWSV15");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Glassfish/fiss_wsdl/balanceInquiry/CBAcctInqWSV15.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MTVNCWCBACCTINQWSV15_WSDL_LOCATION = url;
        MTVNCWCBACCTINQWSV15_EXCEPTION = e;
    }

    public MtvnCWCBAcctInqWSV15() {
        super(__getWsdlLocation(), MTVNCWCBACCTINQWSV15_QNAME);
    }

    public MtvnCWCBAcctInqWSV15(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns MtvnCWCBAcctInqWSV15Interface
     */
    @WebEndpoint(name = "mtvnCWCBAcctInqWSV15Port")
    public MtvnCWCBAcctInqWSV15Interface getMtvnCWCBAcctInqWSV15Port() {
        return super.getPort(new QName("mtvnCBAcctInqWSV15", "mtvnCWCBAcctInqWSV15Port"), MtvnCWCBAcctInqWSV15Interface.class);
    }

    private static URL __getWsdlLocation() {
        if (MTVNCWCBACCTINQWSV15_EXCEPTION!= null) {
            throw MTVNCWCBACCTINQWSV15_EXCEPTION;
        }
        return MTVNCWCBACCTINQWSV15_WSDL_LOCATION;
    }

}
