
package com.smartbt.vtsuite.ws.setProductId;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * CBProdIDMaintWSV1
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.0
 * 
 */
@WebService(name = "mtvnCWCBProdIDMaintWSV1Interface", targetNamespace = "mtvnCBProdIDMaintWSV1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface MtvnCWCBProdIDMaintWSV1Interface {


    /**
     * 
     * @param messagePart
     * @return
     *     returns com.smartbt.vtsuite.ws.setProductId.CBProdIDMaintMtvnSvcRes
     */
    @WebMethod(operationName = "CBProdIDMaint", action = "CBProdIDMaintWSV1:CBProdIDMaintMtvnSvcReqMsg")
    @WebResult(name = "CBProdIDMaintMtvnSvcRes", targetNamespace = "mtvnCWCBProdIDMaintSvcRes", partName = "messagePart")
    public CBProdIDMaintMtvnSvcRes cbProdIDMaint(
        @WebParam(name = "CBProdIDMaintMtvnSvcReq", targetNamespace = "mtvnCWCBProdIDMaintSvcReq", partName = "messagePart")
        CBProdIDMaintMtvnSvcReq messagePart);

}
