
package com.smartbt.vtsuite.ws.setProductId;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "mtvnCWCBProdIDMaintWSV1", targetNamespace = "mtvnCBProdIDMaintWSV1", wsdlLocation = "file:/C:/Glassfish/fiss_wsdl/setProductId/CBProdIDMaintWSV1.wsdl")
public class MtvnCWCBProdIDMaintWSV1
    extends Service
{

    private final static URL MTVNCWCBPRODIDMAINTWSV1_WSDL_LOCATION;
    private final static WebServiceException MTVNCWCBPRODIDMAINTWSV1_EXCEPTION;
    private final static QName MTVNCWCBPRODIDMAINTWSV1_QNAME = new QName("mtvnCBProdIDMaintWSV1", "mtvnCWCBProdIDMaintWSV1");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Glassfish/fiss_wsdl/setProductId/CBProdIDMaintWSV1.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MTVNCWCBPRODIDMAINTWSV1_WSDL_LOCATION = url;
        MTVNCWCBPRODIDMAINTWSV1_EXCEPTION = e;
    }

    public MtvnCWCBProdIDMaintWSV1() {
        super(__getWsdlLocation(), MTVNCWCBPRODIDMAINTWSV1_QNAME);
    }

    public MtvnCWCBProdIDMaintWSV1(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns MtvnCWCBProdIDMaintWSV1Interface
     */
    @WebEndpoint(name = "mtvnCWCBProdIDMaintWSV1Port")
    public MtvnCWCBProdIDMaintWSV1Interface getMtvnCWCBProdIDMaintWSV1Port() {
        return super.getPort(new QName("mtvnCBProdIDMaintWSV1", "mtvnCWCBProdIDMaintWSV1Port"), MtvnCWCBProdIDMaintWSV1Interface.class);
    }

    private static URL __getWsdlLocation() {
        if (MTVNCWCBPRODIDMAINTWSV1_EXCEPTION!= null) {
            throw MTVNCWCBPRODIDMAINTWSV1_EXCEPTION;
        }
        return MTVNCWCBPRODIDMAINTWSV1_WSDL_LOCATION;
    }

}
