
package com.smartbt.vtsuite.ws.setPin;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "mtvnCWCBPinOffsetChgWSV1", targetNamespace = "mtvnCBPinOffsetChgWSV1", wsdlLocation = "file:/C:/Glassfish/fiss_wsdl/setPin/CBPinOffsetChgWSV1.wsdl")
public class MtvnCWCBPinOffsetChgWSV1
    extends Service
{

    private final static URL MTVNCWCBPINOFFSETCHGWSV1_WSDL_LOCATION;
    private final static WebServiceException MTVNCWCBPINOFFSETCHGWSV1_EXCEPTION;
    private final static QName MTVNCWCBPINOFFSETCHGWSV1_QNAME = new QName("mtvnCBPinOffsetChgWSV1", "mtvnCWCBPinOffsetChgWSV1");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Glassfish/fiss_wsdl/setPin/CBPinOffsetChgWSV1.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MTVNCWCBPINOFFSETCHGWSV1_WSDL_LOCATION = url;
        MTVNCWCBPINOFFSETCHGWSV1_EXCEPTION = e;
    }

    public MtvnCWCBPinOffsetChgWSV1() {
        super(__getWsdlLocation(), MTVNCWCBPINOFFSETCHGWSV1_QNAME);
    }

    public MtvnCWCBPinOffsetChgWSV1(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns MtvnCWCBPinOffsetChgWSV1Interface
     */
    @WebEndpoint(name = "mtvnCWCBPinOffsetChgWSV1Port")
    public MtvnCWCBPinOffsetChgWSV1Interface getMtvnCWCBPinOffsetChgWSV1Port() {
        return super.getPort(new QName("mtvnCBPinOffsetChgWSV1", "mtvnCWCBPinOffsetChgWSV1Port"), MtvnCWCBPinOffsetChgWSV1Interface.class);
    }

    private static URL __getWsdlLocation() {
        if (MTVNCWCBPINOFFSETCHGWSV1_EXCEPTION!= null) {
            throw MTVNCWCBPINOFFSETCHGWSV1_EXCEPTION;
        }
        return MTVNCWCBPINOFFSETCHGWSV1_WSDL_LOCATION;
    }

}
