
package com.smartbt.vtsuite.ws.setPin;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * CBPinOffsetChgWSV1
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.0
 * 
 */
@WebService(name = "mtvnCWCBPinOffsetChgWSV1Interface", targetNamespace = "mtvnCBPinOffsetChgWSV1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface MtvnCWCBPinOffsetChgWSV1Interface {


    /**
     * 
     * @param messagePart
     * @return
     *     returns com.smartbt.vtsuite.ws.setPin.CBPinOffsetChgMtvnSvcRes
     */
    @WebMethod(operationName = "CBPinOffsetChg", action = "CBPinOffsetChgWSV1:CBPinOffsetChgMtvnSvcReqMsg")
    @WebResult(name = "CBPinOffsetChgMtvnSvcRes", targetNamespace = "mtvnCWCBPinOffsetChgSvcRes", partName = "messagePart")
    public CBPinOffsetChgMtvnSvcRes cbPinOffsetChg(
        @WebParam(name = "CBPinOffsetChgMtvnSvcReq", targetNamespace = "mtvnCWCBPinOffsetChgSvcReq", partName = "messagePart")
        CBPinOffsetChgMtvnSvcReq messagePart);

}
