
package com.smartbt.vtsuite.ws.history.pending;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "mtvnCWCBPndTxnInqWSV7", targetNamespace = "mtvnCBPndTxnInqWSV7", wsdlLocation = "file:/C:/Glassfish/fiss_wsdl/history/pending/CBPndTxnInqWSV7.wsdl")
public class MtvnCWCBPndTxnInqWSV7
    extends Service
{

    private final static URL MTVNCWCBPNDTXNINQWSV7_WSDL_LOCATION;
    private final static WebServiceException MTVNCWCBPNDTXNINQWSV7_EXCEPTION;
    private final static QName MTVNCWCBPNDTXNINQWSV7_QNAME = new QName("mtvnCBPndTxnInqWSV7", "mtvnCWCBPndTxnInqWSV7");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Glassfish/fiss_wsdl/history/pending/CBPndTxnInqWSV7.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MTVNCWCBPNDTXNINQWSV7_WSDL_LOCATION = url;
        MTVNCWCBPNDTXNINQWSV7_EXCEPTION = e;
    }

    public MtvnCWCBPndTxnInqWSV7() {
        super(__getWsdlLocation(), MTVNCWCBPNDTXNINQWSV7_QNAME);
    }

    public MtvnCWCBPndTxnInqWSV7(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns MtvnCWCBPndTxnInqWSV7Interface
     */
    @WebEndpoint(name = "mtvnCWCBPndTxnInqWSV7Port")
    public MtvnCWCBPndTxnInqWSV7Interface getMtvnCWCBPndTxnInqWSV7Port() {
        return super.getPort(new QName("mtvnCBPndTxnInqWSV7", "mtvnCWCBPndTxnInqWSV7Port"), MtvnCWCBPndTxnInqWSV7Interface.class);
    }

    private static URL __getWsdlLocation() {
        if (MTVNCWCBPNDTXNINQWSV7_EXCEPTION!= null) {
            throw MTVNCWCBPNDTXNINQWSV7_EXCEPTION;
        }
        return MTVNCWCBPNDTXNINQWSV7_WSDL_LOCATION;
    }

}
