
package com.smartbt.vtsuite.ws.history.pending;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * CBPndTxnInqWSV7
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.0
 * 
 */
@WebService(name = "mtvnCWCBPndTxnInqWSV7Interface", targetNamespace = "mtvnCBPndTxnInqWSV7")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface MtvnCWCBPndTxnInqWSV7Interface {


    /**
     * 
     * @param messagePart
     * @return
     *     returns com.smartbt.vtsuite.ws.history.pending.CBPndTxnInqMtvnSvcRes
     */
    @WebMethod(operationName = "CBPndTxnInq", action = "CBPndTxnInqWSV7:CBPndTxnInqMtvnSvcReqMsg")
    @WebResult(name = "CBPndTxnInqMtvnSvcRes", targetNamespace = "mtvnCWCBPndTxnInqSvcRes", partName = "messagePart")
    public CBPndTxnInqMtvnSvcRes cbPndTxnInq(
        @WebParam(name = "CBPndTxnInqMtvnSvcReq", targetNamespace = "mtvnCWCBPndTxnInqSvcReq", partName = "messagePart")
        CBPndTxnInqMtvnSvcReq messagePart);

}
