
package com.smartbt.vtsuite.ws.history.details;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * CBHistTxnDtlInqWSV6
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.0
 * 
 */
@WebService(name = "mtvnCWCBHistTxnDtlInqWSV6Interface", targetNamespace = "mtvnCBHistTxnDtlInqWSV6")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface MtvnCWCBHistTxnDtlInqWSV6Interface {


    /**
     * 
     * @param messagePart
     * @return
     *     returns com.smartbt.vtsuite.ws.history.details.CBHistTxnDtlInqMtvnSvcRes
     */
    @WebMethod(operationName = "CBHistTxnDtlInq", action = "CBHistTxnDtlInqWSV6:CBHistTxnDtlInqMtvnSvcReqMsg")
    @WebResult(name = "CBHistTxnDtlInqMtvnSvcRes", targetNamespace = "mtvnCWCBHistTxnDtlInqSvcRes", partName = "messagePart")
    public CBHistTxnDtlInqMtvnSvcRes cbHistTxnDtlInq(
        @WebParam(name = "CBHistTxnDtlInqMtvnSvcReq", targetNamespace = "mtvnCWCBHistTxnDtlInqSvcReq", partName = "messagePart")
        CBHistTxnDtlInqMtvnSvcReq messagePart);

}
