
package com.smartbt.vtsuite.ws.history.details;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "mtvnCWCBHistTxnDtlInqWSV6", targetNamespace = "mtvnCBHistTxnDtlInqWSV6", wsdlLocation = "file:/C:/Glassfish/fiss_wsdl/history/details/CBHistTxnDtlInqWSV6.wsdl")
public class MtvnCWCBHistTxnDtlInqWSV6
    extends Service
{

    private final static URL MTVNCWCBHISTTXNDTLINQWSV6_WSDL_LOCATION;
    private final static WebServiceException MTVNCWCBHISTTXNDTLINQWSV6_EXCEPTION;
    private final static QName MTVNCWCBHISTTXNDTLINQWSV6_QNAME = new QName("mtvnCBHistTxnDtlInqWSV6", "mtvnCWCBHistTxnDtlInqWSV6");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Glassfish/fiss_wsdl/history/details/CBHistTxnDtlInqWSV6.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MTVNCWCBHISTTXNDTLINQWSV6_WSDL_LOCATION = url;
        MTVNCWCBHISTTXNDTLINQWSV6_EXCEPTION = e;
    }

    public MtvnCWCBHistTxnDtlInqWSV6() {
        super(__getWsdlLocation(), MTVNCWCBHISTTXNDTLINQWSV6_QNAME);
    }

    public MtvnCWCBHistTxnDtlInqWSV6(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns MtvnCWCBHistTxnDtlInqWSV6Interface
     */
    @WebEndpoint(name = "mtvnCWCBHistTxnDtlInqWSV6Port")
    public MtvnCWCBHistTxnDtlInqWSV6Interface getMtvnCWCBHistTxnDtlInqWSV6Port() {
        return super.getPort(new QName("mtvnCBHistTxnDtlInqWSV6", "mtvnCWCBHistTxnDtlInqWSV6Port"), MtvnCWCBHistTxnDtlInqWSV6Interface.class);
    }

    private static URL __getWsdlLocation() {
        if (MTVNCWCBHISTTXNDTLINQWSV6_EXCEPTION!= null) {
            throw MTVNCWCBHISTTXNDTLINQWSV6_EXCEPTION;
        }
        return MTVNCWCBHISTTXNDTLINQWSV6_WSDL_LOCATION;
    }

}
